PROGRAM WRAP_LACDYN

USE PARKIND1,  ONLY : JPIM, JPRB
USE YOMGMV,    ONLY : TGMV
USE YOMOROG,   ONLY : TOROG
USE YOMGSGEOM, ONLY : TGSGEOM
USE YOMDIMV  , ONLY : YRDIMV

USE COPY_TDIM_MOD
USE COPY_TDIMV_MOD
USE COPY_TDYN_MOD
USE COPY_TGEM_MOD
USE COPY_TGMV_MOD
USE COPY_TGSGEOM_MOD
USE COPY_TLDDH_MOD
USE COPY_TMDDH_MOD
USE COPY_TOROG_MOD
USE COPY_TPARAR_MOD
USE COPY_TPHY_MOD
USE COPY_TSTA_MOD
USE COPY_TVAB_MOD
USE COPY_TVETA_MOD
USE COPY_TVFE_MOD
USE COPY_TYPE_GFLD_MOD

USE LOAD_MOD
#ifdef USE_ACC
USE CUDAFOR
#endif
USE OMP_LIB

USE YOMDIM   
USE YOMDIMV  
USE YOMDYN   
USE YOMGSGEOM
USE YOMLDDH  
USE YOMMDDH  
USE YOMSTA   
USE YOMVERT 
USE YOM_YGFL 
USE YOMPARAR 
USE YOMGEM   
USE YOMPHY   

USE XRD_GETOPTIONS


IMPLICIT NONE

INTERFACE CPRS
  PROCEDURE CPRS1, CPRS2, CPRS3, CPRSI1, CPRS_TOROG, CPRS_GSGEOM
END INTERFACE

INTERFACE REALO
  PROCEDURE REALOX1, REALOX2, REALOX3, REALOI1, REALO_TOROG, REALO_GSGEOM
END INTERFACE

INTERFACE SETALL
  PROCEDURE SETALLI1
  PROCEDURE SETALLI2
  PROCEDURE SETALLX1
  PROCEDURE SETALLX2
  PROCEDURE SETALLX3
  PROCEDURE SETALL_GMV
  PROCEDURE SETALL_TGSGEOM
  PROCEDURE SETALL_TOROG
END INTERFACE

INTERFACE DDIFF
  PROCEDURE DDIFFX1
  PROCEDURE DDIFFX2
  PROCEDURE DDIFFX3
END INTERFACE

INTEGER(KIND=JPIM), ALLOCATABLE  :: IFDIA (:)

TYPE(TGMV)        , POINTER      :: YDGMV_ALL(:)
INTEGER(KIND=JPIM)               :: KIDIA 
INTEGER(KIND=JPIM)               :: KFDIA 
INTEGER(KIND=JPIM), POINTER      :: KSETTLOFF_ALL(:,:)
REAL(KIND=JPRB)                  :: PBETADT 
REAL(KIND=JPRB)                  :: PDT 
REAL(KIND=JPRB)   , POINTER      :: PSLHDA_ALL(:,:)
REAL(KIND=JPRB)   , POINTER      :: PSLHDD0_ALL(:,:)
TYPE(TGSGEOM)     , POINTER      :: YDGSGEOM_ALL(:) 
TYPE(TOROG)       , POINTER      :: YDOROG_ALL(:)
REAL(KIND=JPRB)   , POINTER      :: POROGL_ALL(:,:)
REAL(KIND=JPRB)   , POINTER      :: POROGM_ALL(:,:) 
REAL(KIND=JPRB)   , POINTER      :: PVCRSSA9F_ALL(:,:,:) 
REAL(KIND=JPRB)   , POINTER      :: PNHXT9_ALL(:,:,:) 
REAL(KIND=JPRB)   , POINTER      :: PVCRS0_ALL(:,:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PVCW0F_ALL(:,:,:) 
REAL(KIND=JPRB)   , POINTER      :: PWDLW0F_ALL(:,:,:) 
REAL(KIND=JPRB)   , POINTER      :: PRDLR0_ALL(:,:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PRDLR9_ALL(:,:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PNHXT0_ALL(:,:,:) 
REAL(KIND=JPRB)   , POINTER      :: PRES0_ALL(:,:,:) 
REAL(KIND=JPRB)   , POINTER      :: PRDELP0_ALL(:,:,:) 
REAL(KIND=JPRB)   , POINTER      :: PCTY0_ALL(:,:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PUVH0_ALL(:,:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PATND_ALL(:,:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PDBBC_ALL(:,:)
REAL(KIND=JPRB)   , POINTER      :: PRDPHI_ALL(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PGWT0_ALL(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PGWT9_ALL(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PGFL_ALL(:,:,:,:) 
REAL(KIND=JPRB)   , POINTER      :: PGMV_ALL(:,:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PGMVS_ALL(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PB1_ALL(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PB2_ALL(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PGMVT1_ALL(:,:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PGMVT1S_ALL(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PGWS_ALL(:,:)
REAL(KIND=JPRB)   , POINTER      :: PGMVTNDSI_ALL(:,:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PWRL95_ALL(:,:,:)

INTEGER(KIND=JPIM), POINTER      :: KSETTLOFF_(:)
REAL(KIND=JPRB)   , POINTER      :: PSLHDA_(:)
REAL(KIND=JPRB)   , POINTER      :: PSLHDD0_(:)
TYPE(TGSGEOM)                    :: YDGSGEOM_
TYPE(TOROG)                      :: YDOROG_
REAL(KIND=JPRB)   , POINTER      :: POROGL_(:)
REAL(KIND=JPRB)   , POINTER      :: POROGM_(:) 
REAL(KIND=JPRB)   , POINTER      :: PVCRSSA9F_(:,:) 
REAL(KIND=JPRB)   , POINTER      :: PNHXT9_(:,:) 
REAL(KIND=JPRB)   , POINTER      :: PVCRS0_(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PVCW0F_(:,:) 
REAL(KIND=JPRB)   , POINTER      :: PWDLW0F_(:,:) 
REAL(KIND=JPRB)   , POINTER      :: PRDLR0_(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PRDLR9_(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PNHXT0_(:,:) 
REAL(KIND=JPRB)   , POINTER      :: PRES0_(:,:) 
REAL(KIND=JPRB)   , POINTER      :: PRDELP0_(:,:) 
REAL(KIND=JPRB)   , POINTER      :: PCTY0_(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PUVH0_(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PATND_(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PDBBC_(:)
REAL(KIND=JPRB)   , POINTER      :: PRDPHI_(:,:)
REAL(KIND=JPRB)   , POINTER      :: PGWT0_(:,:)
REAL(KIND=JPRB)   , POINTER      :: PGWT9_(:,:)
REAL(KIND=JPRB)   , POINTER      :: PGFL_(:,:,:) 
REAL(KIND=JPRB)   , POINTER      :: PGMV_(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PGMVS_(:,:)
REAL(KIND=JPRB)   , POINTER      :: PB1_(:,:)
REAL(KIND=JPRB)   , POINTER      :: PB2_(:,:)
REAL(KIND=JPRB)   , POINTER      :: PGMVT1_(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PGMVT1S_(:,:)
REAL(KIND=JPRB)   , POINTER      :: PGWS_(:)
REAL(KIND=JPRB)   , POINTER      :: PGMVTNDSI_(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PWRL95_(:,:)

REAL(KIND=JPRB)   , POINTER      :: PGMV_ALL1 (:,:,:,:)

INTEGER :: IBL, ICOUNT, KLON, JJ, JIDIA, JFDIA
INTEGER :: ICOUNT1, KLON1
INTEGER :: ICOUNT0, KLON0
LOGICAL :: LLDIFF, LLPRINT
CHARACTER (LEN=32) :: CLCASE
INTEGER, POINTER :: IDIFFBLOCK (:) => NULL ()
INTEGER (KIND=8) :: HEAPSIZE
INTEGER (KIND=4) :: HEAPSIZE4
INTEGER (KIND=4) :: ISTAT
INTEGER :: NTIMES, ITIME
REAL(KIND=8) :: TSC, TEC, TSD, TED, ZTC, ZTD
LOGICAL :: LLSINGLEBLOCK, LLFIXARRAYS

#include "lacdyn.intfb.h"
#include "abor1.intfb.h"

YDGSGEOM_ALL => NULL ()

CALL INITOPTIONS ()
CALL GETOPTION ("--case", CLCASE, MND = .TRUE.)
CALL GETOPTION ("--diff", LLDIFF)
CALL GETOPTION ("--diff-block-list", IDIFFBLOCK)
ICOUNT1 = 0 
CALL GETOPTION ("--count", ICOUNT1)
KLON1 = 0 
HEAPSIZE4 = 0
CALL GETOPTION ("--heapsize", HEAPSIZE4)
NTIMES = 1
CALL GETOPTION ("--times", NTIMES)
LLSINGLEBLOCK = .FALSE.
CALL GETOPTION ("--single-block", LLSINGLEBLOCK)
CALL GETOPTION ("--fix-arrays", LLFIXARRAYS)
CALL CHECKOPTIONS ()

#ifdef USE_ACC
IF (HEAPSIZE4 > 0) THEN
HEAPSIZE = HEAPSIZE4*1024_8*1024_8
ISTAT = CUDADEVICESETLIMIT (CUDALIMITMALLOCHEAPSIZE, HEAPSIZE)
ENDIF

CALL CUDAPROFILERSTOP
#endif



OPEN (77, FORM='FORMATTED', FILE=TRIM (CLCASE)//'/LACDYN.COUNT')
READ (77, *) ICOUNT
CLOSE (77)

IF (ICOUNT1 == 0) ICOUNT1 = ICOUNT

ALLOCATE (IFDIA (ICOUNT))

CALL LACDYN_LOAD_ALL (TRIM (CLCASE)//"/LACDYN.CONST")

CALL OPEN_LOAD (TRIM (CLCASE)//"/LACDYN")

PRINT *, "-- READ"

DO IBL = 1, ICOUNT

  PRINT *, IBL

#define SET(x) CALL SETALL (x##_ALL)

  SET (YDGMV)
  CALL LOAD (ILUN_IN, KIDIA)
  CALL LOAD (ILUN_IN, IFDIA (IBL))
  IF (IBL == 1) KLON = IFDIA (IBL)
  IF (KLON1 == 0) KLON1 = KLON
  CALL LOAD (ILUN_IN, PBETADT)
  CALL LOAD (ILUN_IN, PDT)
  SET (YDGSGEOM)
  SET (YDOROG)
  SET (PSLHDA)
  SET (PSLHDD0)
  CALL SETALL (KSETTLOFF_ALL, .FALSE.)
  SET (POROGL)
  SET (POROGM)
  CALL SETALL (PVCRSSA9F_ALL, .FALSE.)
  SET (PNHXT9)
  CALL SETALL (PVCRS0_ALL, .FALSE.)
  CALL SETALL (PVCW0F_ALL, .FALSE.)
  CALL SETALL (PWDLW0F_ALL, .FALSE.)
  CALL SETALL (PRDLR0_ALL, .FALSE.)
  CALL SETALL (PRDLR9_ALL, .FALSE.)
  SET (PNHXT0)
  SET (PRES0)
  SET (PRDELP0)
  SET (PCTY0)
  SET (PUVH0)
  SET (PATND)
  CALL SETALL (PDBBC_ALL, .FALSE.)
  CALL SETALL (PRDPHI_ALL, .FALSE.)
  CALL SETALL (PGWT0_ALL, .FALSE.)
  CALL SETALL (PGWT9_ALL, .FALSE.)
  SET (PGFL)
  SET (PGMV)
  SET (PGMVS)
  SET (PB1)
  SET (PB2)
  SET (PGMVT1)
  SET (PGMVT1S)
  CALL SETALL (PGWS_ALL, .FALSE.)
! SET (PGMVTNDSI)
  SET (PWRL95)

#undef SET

ENDDO

IF (LLFIXARRAYS) THEN
  ALLOCATE (PGMV_ALL1 (SIZE (PGMV_ALL, 1), SIZE (PGMV_ALL, 2), &
                       SIZE (PGMV_ALL, 3) + 1, SIZE (PGMV_ALL, 4)))
  PGMV_ALL1 (:,:,1:SIZE (PGMV_ALL, 3),:) = PGMV_ALL
  DEALLOCATE (PGMV_ALL)
  PGMV_ALL => PGMV_ALL1
  YDGMV_ALL%NDIMGMV = YDGMV_ALL%NDIMGMV + 1
ENDIF


KLON0 = KLON; ICOUNT0 = ICOUNT
KLON = KLON1; ICOUNT = ICOUNT1

KIDIA = 1
KFDIA = KLON

ALLOCATE (PGMVTNDSI_ALL (KLON, YRDIMV%NFLEVG,YRMDDH%NDIMSIGMV, ICOUNT))

PRINT *, "-- RUN"

#ifdef USE_ACC
CALL CUDAPROFILERSTART 
#endif

!$acc enter data create (YRVFE)     
CALL COPY (YRVFE)     
!$acc enter data create (YRLDDH)    
CALL COPY (YRLDDH)    
!$acc enter data create (YRSTA)     
CALL COPY (YRSTA)     
!$acc enter data create (YRVAB)     
CALL COPY (YRVAB)     
!$acc enter data create (YRPARAR)   
CALL COPY (YRPARAR)   
!$acc enter data create (YRVETA)    
CALL COPY (YRVETA)    
!$acc enter data create (YRGEM)     
CALL COPY (YRGEM)     
!$acc enter data create (YRPHY)     
CALL COPY (YRPHY)     
!$acc enter data create (YRDIM)     
CALL COPY (YRDIM)     
!$acc enter data create (YRDIMV)    
CALL COPY (YRDIMV)    
!$acc enter data create (YRDYN)     
CALL COPY (YRDYN)     
!$acc enter data create (YRMDDH)    
CALL COPY (YRMDDH)    
!$acc enter data create (YGFL)      
CALL COPY (YGFL)      
!$acc enter data create (YDGMV_ALL(1))     
CALL COPY (YDGMV_ALL(1))     

!$acc enter data create (YDGSGEOM_ALL)
DO IBL = 1, SIZE (YDGSGEOM_ALL)
  CALL COPY (YDGSGEOM_ALL (IBL))
ENDDO

!$acc enter data create (YDOROG_ALL)
DO IBL = 1, SIZE (YDOROG_ALL)
  CALL COPY (YDOROG_ALL (IBL))
ENDDO

IF (.NOT. LLSINGLEBLOCK) THEN

#ifdef USE_ACC

CALL ABOR1 ('WRAP_LACDYN: MULTIPLE BLOCKS NOT WORKING WITH OPENACC');

#else
DO ITIME = 1, NTIMES

    TSD = OMP_GET_WTIME ()

    TSC = OMP_GET_WTIME ()

DO IBL = 1, ICOUNT

    JIDIA = 1
    JFDIA = KLON

    CALL LACDYN(YRVFE,YRLDDH,YRSTA,YRVAB,YRPARAR,YRVETA,YRGEM,YRPHY,YGFL,&
     & YRMDDH,YRDYN,YRDIMV,YRDIM,KLON,YDGMV_ALL(1),JIDIA,JFDIA,PBETADT,PDT,&
     & PSLHDA_ALL(:,IBL),PSLHDD0_ALL(:,IBL),YDGSGEOM_ALL(IBL),YDOROG_ALL(IBL),POROGL_ALL(:,IBL),&
     & POROGM_ALL(:,IBL),PVCRSSA9F_ALL(:,:,IBL),PNHXT9_ALL(:,:,IBL),&
     & PVCRS0_ALL(:,:,:,IBL),PVCW0F_ALL(:,:,IBL),PWDLW0F_ALL(:,:,IBL),&
     & PRDLR0_ALL(:,:,:,IBL),PRDLR9_ALL(:,:,:,IBL),PNHXT0_ALL(:,:,IBL),&
     & PRES0_ALL(:,:,IBL),PRDELP0_ALL(:,:,IBL),PCTY0_ALL(:,:,:,IBL),PUVH0_ALL(:,:,:,IBL),&
     & PATND_ALL(:,:,:,IBL),PDBBC_ALL(:,IBL),PRDPHI_ALL(:,:,IBL),PGWT0_ALL(:,:,IBL),&
     & PGWT9_ALL(:,:,IBL),PGFL_ALL(:,:,:,IBL),&
     & KSETTLOFF_ALL(:,IBL),PGMV_ALL(:,:,:,IBL),PGMVS_ALL(:,:,IBL),PB1_ALL(:,:,IBL),&
     & PB2_ALL(:,:,IBL),PGMVT1_ALL(:,:,:,IBL),PGMVT1S_ALL(:,:,IBL),PGWS_ALL(:,IBL),&
     & PGMVTNDSI_ALL(:,:,:,IBL),PWRL95_ALL(:,:,IBL))

ENDDO

    TEC = OMP_GET_WTIME ()

    TED = OMP_GET_WTIME ()

    ZTC = ZTC + (TEC - TSC)
    ZTD = ZTD + (TED - TSD)

ENDDO

PRINT *, " ZTD = ", ZTD, ZTD / REAL (ICOUNT1 * KLON, JPRB)
PRINT *, " ZTC = ", ZTC, ZTC / REAL (ICOUNT1 * KLON, JPRB)

#endif

ELSE


#define realo(x) CALL REALO (x##_ALL, x##_)

realo (KSETTLOFF); realo (PSLHDA); realo (PSLHDD0); realo (YDGSGEOM);
realo (YDOROG); realo (POROGL); realo (POROGM); realo (PVCRSSA9F);
realo (PNHXT9); realo (PVCRS0); realo (PVCW0F); realo (PWDLW0F);
realo (PRDLR0); realo (PRDLR9); realo (PNHXT0); realo (PRES0);
realo (PRDELP0); realo (PCTY0); realo (PUVH0); realo (PATND);
realo (PDBBC); realo (PRDPHI); realo (PGWT0); realo (PGWT9);
realo (PGFL); realo (PGMV); realo (PGMVS); realo (PB1); realo (PB2);
realo (PGMVT1); realo (PGMVT1S); realo (PGWS); realo (PGMVTNDSI);
realo (PWRL95);

#undef realo


!$acc enter data create (YDGSGEOM_)
CALL COPY (YDGSGEOM_)
CALL CPRS (YDGSGEOM_ALL, YDGSGEOM_, .TRUE.)

!$acc enter data create (YDOROG_)
CALL COPY (YDOROG_)
CALL CPRS (YDOROG_ALL, YDOROG_, .TRUE.)

DO ITIME = 1, NTIMES

    TSD = OMP_GET_WTIME ()

!$acc data &
!$acc create  (PSLHDA_, PSLHDD0_, POROGL_, POROGM_, PVCRSSA9F_, PNHXT9_, PVCRS0_, PVCW0F_, PWDLW0F_, PRDLR0_,  &
!$acc          PRDLR9_, PNHXT0_, PRES0_, PRDELP0_, PCTY0_, PUVH0_, PATND_, PDBBC_, PRDPHI_, PGWT0_, PGWT9_,    &
!$acc          PGFL_, PGMV_, PGMVS_, PB1_, PB2_, PGMVT1_, PGMVT1S_, PGWS_, PGMVTNDSI_, PWRL95_, KSETTLOFF_)    &
!$acc present (YRVFE, YRLDDH, YRSTA, YRVAB, YRPARAR, YRVETA, YRGEM, YRPHY, YGFL, YRMDDH, YRDYN, YRDIMV, YRDIM, &
!$acc          YDGMV_ALL(1), YDGSGEOM_, YDOROG_)

#define cpi(x) CALL CPRS (x##_ALL, x##_, .TRUE.)

cpi (PSLHDA); cpi (PSLHDD0); cpi (POROGL); cpi (POROGM); cpi (PVCRSSA9F); cpi (PNHXT9); 
cpi (PVCRS0); cpi (PVCW0F); cpi (PWDLW0F); cpi (PRDLR0); cpi (PRDLR9); cpi (PNHXT0); 
cpi (PRES0); cpi (PRDELP0); cpi (PCTY0); cpi (PUVH0); cpi (PATND); cpi (PDBBC); 
cpi (PRDPHI); cpi (PGWT0); cpi (PGFL); cpi (PGMV); cpi (PGMVS); cpi (PB1); cpi (PB2); 
cpi (PGMVT1); cpi (PGMVT1S); cpi (PGWS); cpi (PGMVTNDSI); 

#undef cpi

    TSC = OMP_GET_WTIME ()

    JIDIA = 1
    JFDIA = KLON*ICOUNT

    CALL LACDYN(YRVFE,YRLDDH,YRSTA,YRVAB,YRPARAR,YRVETA,YRGEM,YRPHY,YGFL,&
     & YRMDDH,YRDYN,YRDIMV,YRDIM,KLON*ICOUNT,YDGMV_ALL(1),JIDIA,JFDIA,PBETADT,PDT,&
     & PSLHDA_, PSLHDD0_, YDGSGEOM_, YDOROG_, POROGL_, &
     & POROGM_, PVCRSSA9F_, PNHXT9_, &
     & PVCRS0_, PVCW0F_, PWDLW0F_, &
     & PRDLR0_, PRDLR9_, PNHXT0_, &
     & PRES0_, PRDELP0_, PCTY0_, PUVH0_, &
     & PATND_, PDBBC_, PRDPHI_, PGWT0_, &
     & PGWT9_, PGFL_, &
     & KSETTLOFF_, PGMV_, PGMVS_, PB1_, &
     & PB2_, PGMVT1_, PGMVT1S_, PGWS_, &
     & PGMVTNDSI_, PWRL95_)

    TEC = OMP_GET_WTIME ()

#define cpo(x) CALL CPRS (x##_ALL, x##_, .FALSE.)

cpo (PGMV ); cpo (PGMVS ); cpo (PB1 ); cpo (PB2 ); cpo (PGMVT1 );
cpo (PGMVT1S ); cpo (PGWS ); cpo (PGMVTNDSI); cpo (PWRL95 ); cpo (KSETTLOFF);

#undef cpo

!$acc end data

    TED = OMP_GET_WTIME ()

    ZTC = ZTC + (TEC - TSC)
    ZTD = ZTD + (TED - TSD)

ENDDO

PRINT *, " ZTD = ", ZTD, ZTD / REAL (ICOUNT1 * KLON, JPRB)
PRINT *, " ZTC = ", ZTC, ZTC / REAL (ICOUNT1 * KLON, JPRB)


ENDIF


IF (LLFIXARRAYS) THEN
  ALLOCATE (PGMV_ALL1 (SIZE (PGMV_ALL, 1), SIZE (PGMV_ALL, 2), &
                       SIZE (PGMV_ALL, 3) - 1, SIZE (PGMV_ALL, 4)))
  PGMV_ALL1 = PGMV_ALL (:,:,1:SIZE (PGMV_ALL, 3)-1,:)
  DEALLOCATE (PGMV_ALL)
  PGMV_ALL => PGMV_ALL1
  YDGMV_ALL%NDIMGMV = YDGMV_ALL%NDIMGMV - 1
ENDIF


LLPRINT = .TRUE.

IF (LLDIFF .AND. ICOUNT0 == ICOUNT1 .AND. KLON1 == KLON0) THEN

PRINT *, "-- DIFF"

DO IBL = 1, ICOUNT

  PRINT *, " BLOCK = ", IBL

#define DIFF(x) CALL DDIFF (#x, x##_ALL, LLPRINT)

  DIFF (PGMV)
  DIFF (PGMVS)
  DIFF (PB1)
  DIFF (PB2)
  DIFF (PGMVT1)
  DIFF (PGMVT1S)
  DIFF (PGWS)
! DIFF (PGMVTNDSI)
  CALL DDIFF ("PWRL95", PWRL95_ALL, .FALSE.)

#undef DIFF

ENDDO

ENDIF

CALL CLOSE_LOAD

CONTAINS

#include "contains.h"

SUBROUTINE SETALL_GMV (YDGMV_ALL)

TYPE (TGMV), POINTER :: YDGMV_ALL (:)
TYPE (TGMV) :: YLGMV
INTEGER (KIND=JPIM) :: IBL1

IF (IBL == 1) THEN
  ALLOCATE (YDGMV_ALL (ICOUNT1))
ENDIF

IF (IBL <= ICOUNT1) THEN
  CALL LOAD_TGMV (ILUN_IN, YDGMV_ALL (IBL))
ELSE
  CALL LOAD_TGMV (ILUN_IN, YLGMV)
ENDIF

IF (IBL == ICOUNT) THEN
  DO IBL1 = ICOUNT+1, ICOUNT1
    YDGMV_ALL (IBL1) = YDGMV_ALL (1)
  ENDDO
ENDIF

END SUBROUTINE

SUBROUTINE SETALL_TGSGEOM (YDGSGEOM_ALL)

TYPE (TGSGEOM), POINTER :: YDGSGEOM_ALL (:)
TYPE (TGSGEOM) :: YLGSGEOM
INTEGER :: IBL1

IF (IBL == 1) THEN
  ALLOCATE (YDGSGEOM_ALL (ICOUNT1))
ENDIF

IF (IBL <= ICOUNT1) THEN
  CALL LOAD_TGSGEOM (ILUN_IN, YDGSGEOM_ALL (IBL))
ELSE
  CALL LOAD_TGSGEOM (ILUN_IN, YLGSGEOM)
  DEALLOCATE (YLGSGEOM% RCORI  )
  DEALLOCATE (YLGSGEOM% RCORIC )
  DEALLOCATE (YLGSGEOM% GM     )
  DEALLOCATE (YLGSGEOM% GMAPPA )
  DEALLOCATE (YLGSGEOM% GOMVRL )
  DEALLOCATE (YLGSGEOM% GOMVRM )
  DEALLOCATE (YLGSGEOM% GNORDL )
  DEALLOCATE (YLGSGEOM% GNORDM )
ENDIF


IF (IBL == ICOUNT) THEN

  DO IBL1 = ICOUNT+1, ICOUNT1
    ALLOCATE (YDGSGEOM_ALL (IBL1)% RCORI   (KLON))
    ALLOCATE (YDGSGEOM_ALL (IBL1)% RCORIC  (KLON))
    ALLOCATE (YDGSGEOM_ALL (IBL1)% GM      (KLON))
    ALLOCATE (YDGSGEOM_ALL (IBL1)% GMAPPA  (KLON))
    ALLOCATE (YDGSGEOM_ALL (IBL1)% GOMVRL  (KLON))
    ALLOCATE (YDGSGEOM_ALL (IBL1)% GOMVRM  (KLON))
    ALLOCATE (YDGSGEOM_ALL (IBL1)% GNORDL  (KLON))
    ALLOCATE (YDGSGEOM_ALL (IBL1)% GNORDM  (KLON))
  
    YDGSGEOM_ALL (IBL1)% RCORI    = YDGSGEOM_ALL (1)% RCORI  
    YDGSGEOM_ALL (IBL1)% RCORIC   = YDGSGEOM_ALL (1)% RCORIC 
    YDGSGEOM_ALL (IBL1)% GM       = YDGSGEOM_ALL (1)% GM     
    YDGSGEOM_ALL (IBL1)% GMAPPA   = YDGSGEOM_ALL (1)% GMAPPA 
    YDGSGEOM_ALL (IBL1)% GOMVRL   = YDGSGEOM_ALL (1)% GOMVRL 
    YDGSGEOM_ALL (IBL1)% GOMVRM   = YDGSGEOM_ALL (1)% GOMVRM 
    YDGSGEOM_ALL (IBL1)% GNORDL   = YDGSGEOM_ALL (1)% GNORDL 
    YDGSGEOM_ALL (IBL1)% GNORDM   = YDGSGEOM_ALL (1)% GNORDM 
  
  ENDDO

ENDIF

END SUBROUTINE

SUBROUTINE SETALL_TOROG (YDOROG_ALL)

TYPE (TOROG), POINTER :: YDOROG_ALL (:)
TYPE (TOROG) :: YLOROG
INTEGER :: IBL1

IF (IBL == 1) THEN
  ALLOCATE (YDOROG_ALL (ICOUNT1))
ENDIF

IF (IBL <= ICOUNT1) THEN
  CALL LOAD_TOROG (ILUN_IN, YDOROG_ALL (IBL))
ELSE
  CALL LOAD_TOROG (ILUN_IN, YLOROG)
  DEALLOCATE (YLOROG%OROG)
ENDIF

IF (IBL == ICOUNT) THEN

  DO IBL1 = ICOUNT+1, ICOUNT1
    ALLOCATE (YDOROG_ALL (IBL1)% OROG   (KLON))
  
    YDOROG_ALL (IBL1)% OROG    = YDOROG_ALL (1)% OROG  
  
  ENDDO

ENDIF

END SUBROUTINE

SUBROUTINE CPRS3 (X3, X3_, LDH2D)

REAL (KIND=JPRB) :: X3 (:,:,:,:), X3_ (:,:,:)
LOGICAL :: LDH2D

INTEGER :: JLON, JBLK, NLON, NBLK, I, NI, J, NJ

NLON = SIZE (X3, 1)
NI   = SIZE (X3, 2)
NJ   = SIZE (X3, 3)
NBLK = SIZE (X3, 4)

IF (LDH2D) THEN
!$acc parallel loop present (X3_) copyin (X3) collapse (4)
DO JBLK = 1, NBLK
  DO I = 1, NI
  DO J = 1, NJ
    DO JLON = 1, NLON
      X3_ ((JBLK-1)*NLON+JLON,I,J) = X3 (JLON, I, J, JBLK)
    ENDDO
  ENDDO
  ENDDO
ENDDO
!$acc end parallel loop
ELSE
!$acc parallel loop present (X3_) copyout (X3) collapse (4)
DO JBLK = 1, NBLK
  DO I = 1, NI
  DO J = 1, NJ
    DO JLON = 1, NLON
      X3 (JLON, I, J, JBLK) = X3_ ((JBLK-1)*NLON+JLON,I,J) 
    ENDDO
  ENDDO
  ENDDO
ENDDO
!$acc end parallel loop
ENDIF

END SUBROUTINE

SUBROUTINE CPRS2 (X2, X2_, LDH2D)

REAL (KIND=JPRB) :: X2 (:,:,:), X2_ (:,:)
LOGICAL :: LDH2D

INTEGER :: JLON, JBLK, NLON, NBLK, I, NI

NLON = SIZE (X2, 1)
NI   = SIZE (X2, 2)
NBLK = SIZE (X2, 3)

IF (LDH2D) THEN
!$acc parallel loop present (X2_) copyin (X2) collapse (3)
DO JBLK = 1, NBLK
  DO I = 1, NI
    DO JLON = 1, NLON
      X2_ ((JBLK-1)*NLON+JLON,I) = X2 (JLON, I, JBLK)
    ENDDO
  ENDDO
ENDDO
!$acc end parallel loop
ELSE
!$acc parallel loop present (X2_) copyout (X2) collapse (3)
DO JBLK = 1, NBLK
  DO I = 1, NI
    DO JLON = 1, NLON
      X2 (JLON, I, JBLK) = X2_ ((JBLK-1)*NLON+JLON,I) 
    ENDDO
  ENDDO
ENDDO
!$acc end parallel loop
ENDIF

END SUBROUTINE

SUBROUTINE CPRSI1 (X1, X1_, LDH2D)

INTEGER (KIND=JPIM) :: X1 (:,:), X1_ (:)
LOGICAL :: LDH2D

INTEGER :: JLON, JBLK, NLON, NBLK

NLON = SIZE (X1, 1)
NBLK = SIZE (X1, 2)

IF (LDH2D) THEN
!$acc parallel loop present (X1_) copyin (X1) collapse (2)
DO JBLK = 1, NBLK
  DO JLON = 1, NLON
    X1_ ((JBLK-1)*NLON+JLON) = X1 (JLON, JBLK)
  ENDDO
ENDDO
!$acc end parallel loop
ELSE
!$acc parallel loop present (X1_) copyout (X1) collapse (2)
DO JBLK = 1, NBLK
  DO JLON = 1, NLON
    X1 (JLON, JBLK) = X1_ ((JBLK-1)*NLON+JLON) 
  ENDDO
ENDDO
!$acc end parallel loop
ENDIF

END SUBROUTINE

SUBROUTINE CPRS1 (X1, X1_, LDH2D)

REAL (KIND=JPRB) :: X1 (:,:), X1_ (:)
LOGICAL :: LDH2D

INTEGER :: JLON, JBLK, NLON, NBLK

NLON = SIZE (X1, 1)
NBLK = SIZE (X1, 2)

IF (LDH2D) THEN
!$acc parallel loop present (X1_) copyin (X1) collapse (2)
DO JBLK = 1, NBLK
  DO JLON = 1, NLON
    X1_ ((JBLK-1)*NLON+JLON) = X1 (JLON, JBLK)
  ENDDO
ENDDO
!$acc end parallel loop
ELSE
!$acc parallel loop present (X1_) copyout (X1) collapse (2)
DO JBLK = 1, NBLK
  DO JLON = 1, NLON
    X1 (JLON, JBLK) = X1_ ((JBLK-1)*NLON+JLON) 
  ENDDO
ENDDO
!$acc end parallel loop
ENDIF

END SUBROUTINE

SUBROUTINE CPRS_TOROG (X1, X1_, LDH2D)

TYPE (TOROG) :: X1 (:), X1_
LOGICAL :: LDH2D

INTEGER :: JLON, JBLK, NLON, NBLK

NBLK = SIZE (X1, 1)
NLON = SIZE (X1(1)%OROG, 1)

IF (LDH2D) THEN
DO JBLK = 1, NBLK
!$acc parallel loop present (X1_%OROG) copyin (X1 (JBLK)%OROG) 
  DO JLON = 1, SIZE (X1(JBLK)%OROG, 1)
    X1_%OROG ((JBLK-1)*NLON+JLON) = X1 (JBLK)%OROG (JLON)
  ENDDO
!$acc end parallel loop
ENDDO
ELSE
DO JBLK = 1, NBLK
!$acc parallel loop present (X1_%OROG) copyout (X1 (JBLK)%OROG) 
  DO JLON = 1, SIZE (X1(JBLK)%OROG, 1)
    X1 (JBLK)%OROG (JLON) = X1_%OROG ((JBLK-1)*NLON+JLON) 
  ENDDO
!$acc end parallel loop
ENDDO
ENDIF

END SUBROUTINE

SUBROUTINE CPRS_GSGEOM (X1, X1_, LDH2D)

TYPE (TGSGEOM) :: X1 (:), X1_
LOGICAL :: LDH2D

INTEGER :: JLON, JBLK, NLON, NBLK

NBLK = SIZE (X1, 1)
NLON = SIZE (X1(1)%RCORI, 1)

IF (LDH2D) THEN
DO JBLK = 1, NBLK
!$acc parallel loop &
!$acc present (X1_%RCORI, X1_%RCORIC, X1_%GEMU, X1_%GSQM2, X1_%GELAM, X1_%GELAT, X1_%GECLO,     &
!$acc          X1_%GESLO, X1_%GM, X1_%GMAPPA, X1_%GOMVRL, X1_%GOMVRM, X1_%GNORDL, X1_%GNORDM,   &
!$acc          X1_%GNORDLCL, X1_%GNORDMCL, X1_%GNORDMCM, X1_%GAW, X1_%NGPLAT, X1_%NUNIQUEGP)    &
!$acc copyin  (X1 (JBLK)%RCORI, X1 (JBLK)%RCORIC, X1 (JBLK)%GEMU, X1 (JBLK)%GSQM2, X1 (JBLK)%GELAM, &
!$acc          X1 (JBLK)%GELAT, X1 (JBLK)%GECLO, X1 (JBLK)%GESLO, X1 (JBLK)%GM, X1 (JBLK)%GMAPPA,   &
!$acc          X1 (JBLK)%GOMVRL, X1 (JBLK)%GOMVRM, X1 (JBLK)%GNORDL, X1 (JBLK)%GNORDM,              &
!$acc          X1 (JBLK)%GNORDLCL, X1 (JBLK)%GNORDMCL, X1 (JBLK)%GNORDMCM, X1 (JBLK)%GAW,           &
!$acc          X1 (JBLK)%NGPLAT, X1 (JBLK)%NUNIQUEGP)  
  DO JLON = 1, SIZE (X1(JBLK)%RCORI, 1)
    IF (ASSOCIATED (X1_%RCORI    )) X1_%RCORI       ((JBLK-1)*NLON+JLON) = X1 (JBLK)%RCORI     (JLON)
    IF (ASSOCIATED (X1_%RCORIC   )) X1_%RCORIC      ((JBLK-1)*NLON+JLON) = X1 (JBLK)%RCORIC    (JLON)
    IF (ASSOCIATED (X1_%GEMU     )) X1_%GEMU        ((JBLK-1)*NLON+JLON) = X1 (JBLK)%GEMU      (JLON)
    IF (ASSOCIATED (X1_%GSQM2    )) X1_%GSQM2       ((JBLK-1)*NLON+JLON) = X1 (JBLK)%GSQM2     (JLON)
    IF (ASSOCIATED (X1_%GELAM    )) X1_%GELAM       ((JBLK-1)*NLON+JLON) = X1 (JBLK)%GELAM     (JLON)
    IF (ASSOCIATED (X1_%GELAT    )) X1_%GELAT       ((JBLK-1)*NLON+JLON) = X1 (JBLK)%GELAT     (JLON)
    IF (ASSOCIATED (X1_%GECLO    )) X1_%GECLO       ((JBLK-1)*NLON+JLON) = X1 (JBLK)%GECLO     (JLON)
    IF (ASSOCIATED (X1_%GESLO    )) X1_%GESLO       ((JBLK-1)*NLON+JLON) = X1 (JBLK)%GESLO     (JLON)
    IF (ASSOCIATED (X1_%GM       )) X1_%GM          ((JBLK-1)*NLON+JLON) = X1 (JBLK)%GM        (JLON)
    IF (ASSOCIATED (X1_%GMAPPA   )) X1_%GMAPPA      ((JBLK-1)*NLON+JLON) = X1 (JBLK)%GMAPPA    (JLON)
    IF (ASSOCIATED (X1_%GOMVRL   )) X1_%GOMVRL      ((JBLK-1)*NLON+JLON) = X1 (JBLK)%GOMVRL    (JLON)
    IF (ASSOCIATED (X1_%GOMVRM   )) X1_%GOMVRM      ((JBLK-1)*NLON+JLON) = X1 (JBLK)%GOMVRM    (JLON)
    IF (ASSOCIATED (X1_%GNORDL   )) X1_%GNORDL      ((JBLK-1)*NLON+JLON) = X1 (JBLK)%GNORDL    (JLON)
    IF (ASSOCIATED (X1_%GNORDM   )) X1_%GNORDM      ((JBLK-1)*NLON+JLON) = X1 (JBLK)%GNORDM    (JLON)
    IF (ASSOCIATED (X1_%GNORDLCL )) X1_%GNORDLCL    ((JBLK-1)*NLON+JLON) = X1 (JBLK)%GNORDLCL  (JLON)
    IF (ASSOCIATED (X1_%GNORDMCL )) X1_%GNORDMCL    ((JBLK-1)*NLON+JLON) = X1 (JBLK)%GNORDMCL  (JLON)
    IF (ASSOCIATED (X1_%GNORDMCM )) X1_%GNORDMCM    ((JBLK-1)*NLON+JLON) = X1 (JBLK)%GNORDMCM  (JLON)
    IF (ASSOCIATED (X1_%GAW      )) X1_%GAW         ((JBLK-1)*NLON+JLON) = X1 (JBLK)%GAW       (JLON)
    IF (ASSOCIATED (X1_%NGPLAT   )) X1_%NGPLAT      ((JBLK-1)*NLON+JLON) = X1 (JBLK)%NGPLAT    (JLON)
    IF (ASSOCIATED (X1_%NUNIQUEGP)) X1_%NUNIQUEGP   ((JBLK-1)*NLON+JLON) = X1 (JBLK)%NUNIQUEGP (JLON)
  ENDDO
!$acc end parallel loop
ENDDO
ELSE
DO JBLK = 1, NBLK
!$acc parallel loop &
!$acc present (X1_%RCORI, X1_%RCORIC, X1_%GEMU, X1_%GSQM2, X1_%GELAM, X1_%GELAT, X1_%GECLO,     &
!$acc          X1_%GESLO, X1_%GM, X1_%GMAPPA, X1_%GOMVRL, X1_%GOMVRM, X1_%GNORDL, X1_%GNORDM,   &
!$acc          X1_%GNORDLCL, X1_%GNORDMCL, X1_%GNORDMCM, X1_%GAW, X1_%NGPLAT, X1_%NUNIQUEGP)    &
!$acc copyout (X1 (JBLK)%RCORI, X1 (JBLK)%RCORIC, X1 (JBLK)%GEMU, X1 (JBLK)%GSQM2, X1 (JBLK)%GELAM, &
!$acc          X1 (JBLK)%GELAT, X1 (JBLK)%GECLO, X1 (JBLK)%GESLO, X1 (JBLK)%GM, X1 (JBLK)%GMAPPA,   &
!$acc          X1 (JBLK)%GOMVRL, X1 (JBLK)%GOMVRM, X1 (JBLK)%GNORDL, X1 (JBLK)%GNORDM,              &
!$acc          X1 (JBLK)%GNORDLCL, X1 (JBLK)%GNORDMCL, X1 (JBLK)%GNORDMCM, X1 (JBLK)%GAW,           &
!$acc          X1 (JBLK)%NGPLAT, X1 (JBLK)%NUNIQUEGP)  
  DO JLON = 1, SIZE (X1(JBLK)%RCORI, 1)
    IF (ASSOCIATED (X1_%RCORI    )) X1 (JBLK)%RCORI     (JLON) = X1_%RCORI       ((JBLK-1)*NLON+JLON) 
    IF (ASSOCIATED (X1_%RCORIC   )) X1 (JBLK)%RCORIC    (JLON) = X1_%RCORIC      ((JBLK-1)*NLON+JLON) 
    IF (ASSOCIATED (X1_%GEMU     )) X1 (JBLK)%GEMU      (JLON) = X1_%GEMU        ((JBLK-1)*NLON+JLON) 
    IF (ASSOCIATED (X1_%GSQM2    )) X1 (JBLK)%GSQM2     (JLON) = X1_%GSQM2       ((JBLK-1)*NLON+JLON) 
    IF (ASSOCIATED (X1_%GELAM    )) X1 (JBLK)%GELAM     (JLON) = X1_%GELAM       ((JBLK-1)*NLON+JLON) 
    IF (ASSOCIATED (X1_%GELAT    )) X1 (JBLK)%GELAT     (JLON) = X1_%GELAT       ((JBLK-1)*NLON+JLON) 
    IF (ASSOCIATED (X1_%GECLO    )) X1 (JBLK)%GECLO     (JLON) = X1_%GECLO       ((JBLK-1)*NLON+JLON) 
    IF (ASSOCIATED (X1_%GESLO    )) X1 (JBLK)%GESLO     (JLON) = X1_%GESLO       ((JBLK-1)*NLON+JLON) 
    IF (ASSOCIATED (X1_%GM       )) X1 (JBLK)%GM        (JLON) = X1_%GM          ((JBLK-1)*NLON+JLON) 
    IF (ASSOCIATED (X1_%GMAPPA   )) X1 (JBLK)%GMAPPA    (JLON) = X1_%GMAPPA      ((JBLK-1)*NLON+JLON) 
    IF (ASSOCIATED (X1_%GOMVRL   )) X1 (JBLK)%GOMVRL    (JLON) = X1_%GOMVRL      ((JBLK-1)*NLON+JLON) 
    IF (ASSOCIATED (X1_%GOMVRM   )) X1 (JBLK)%GOMVRM    (JLON) = X1_%GOMVRM      ((JBLK-1)*NLON+JLON) 
    IF (ASSOCIATED (X1_%GNORDL   )) X1 (JBLK)%GNORDL    (JLON) = X1_%GNORDL      ((JBLK-1)*NLON+JLON) 
    IF (ASSOCIATED (X1_%GNORDM   )) X1 (JBLK)%GNORDM    (JLON) = X1_%GNORDM      ((JBLK-1)*NLON+JLON) 
    IF (ASSOCIATED (X1_%GNORDLCL )) X1 (JBLK)%GNORDLCL  (JLON) = X1_%GNORDLCL    ((JBLK-1)*NLON+JLON) 
    IF (ASSOCIATED (X1_%GNORDMCL )) X1 (JBLK)%GNORDMCL  (JLON) = X1_%GNORDMCL    ((JBLK-1)*NLON+JLON) 
    IF (ASSOCIATED (X1_%GNORDMCM )) X1 (JBLK)%GNORDMCM  (JLON) = X1_%GNORDMCM    ((JBLK-1)*NLON+JLON) 
    IF (ASSOCIATED (X1_%GAW      )) X1 (JBLK)%GAW       (JLON) = X1_%GAW         ((JBLK-1)*NLON+JLON) 
    IF (ASSOCIATED (X1_%NGPLAT   )) X1 (JBLK)%NGPLAT    (JLON) = X1_%NGPLAT      ((JBLK-1)*NLON+JLON) 
    IF (ASSOCIATED (X1_%NUNIQUEGP)) X1 (JBLK)%NUNIQUEGP (JLON) = X1_%NUNIQUEGP   ((JBLK-1)*NLON+JLON) 
  ENDDO
!$acc end parallel loop
ENDDO
ENDIF

END SUBROUTINE

SUBROUTINE REALOX1 (X1, X1_)
REAL (KIND=JPRB), POINTER :: X1 (:,:), X1_ (:)
ALLOCATE (X1_ (SIZE (X1, 1) * SIZE (X1, 2)))
END SUBROUTINE

SUBROUTINE REALOI1 (I1, I1_)
INTEGER (KIND=JPIM), POINTER :: I1 (:,:), I1_ (:)
ALLOCATE (I1_ (SIZE (I1, 1) * SIZE (I1, 2)))
END SUBROUTINE

SUBROUTINE REALOX2 (X2, X2_)
REAL (KIND=JPRB), POINTER :: X2 (:,:,:), X2_ (:,:)
ALLOCATE (X2_ (SIZE (X2, 1) * SIZE (X2, 3), SIZE (X2, 2)))
END SUBROUTINE

SUBROUTINE REALOX3 (X3, X3_)
REAL (KIND=JPRB), POINTER :: X3 (:,:,:,:), X3_ (:,:,:)
ALLOCATE (X3_ (SIZE (X3, 1) * SIZE (X3, 4), SIZE (X3, 2), SIZE (X3, 3)))
END SUBROUTINE

SUBROUTINE REALO_TOROG (X1, X1_)

TYPE (TOROG) :: X1 (:), X1_

ALLOCATE (X1_%OROG (SIZE (X1) * SIZE (X1(1)%OROG)))

END SUBROUTINE

SUBROUTINE REALO_GSGEOM (X1, X1_)

TYPE (TGSGEOM) :: X1 (:), X1_

IF (ASSOCIATED (X1 (1)%RCORI    )) ALLOCATE (X1_%RCORI       (SIZE (X1) * SIZE (X1 (1)%RCORI     )))
IF (ASSOCIATED (X1 (1)%RCORIC   )) ALLOCATE (X1_%RCORIC      (SIZE (X1) * SIZE (X1 (1)%RCORIC    )))
IF (ASSOCIATED (X1 (1)%GEMU     )) ALLOCATE (X1_%GEMU        (SIZE (X1) * SIZE (X1 (1)%GEMU      )))
IF (ASSOCIATED (X1 (1)%GSQM2    )) ALLOCATE (X1_%GSQM2       (SIZE (X1) * SIZE (X1 (1)%GSQM2     )))
IF (ASSOCIATED (X1 (1)%GELAM    )) ALLOCATE (X1_%GELAM       (SIZE (X1) * SIZE (X1 (1)%GELAM     )))
IF (ASSOCIATED (X1 (1)%GELAT    )) ALLOCATE (X1_%GELAT       (SIZE (X1) * SIZE (X1 (1)%GELAT     )))
IF (ASSOCIATED (X1 (1)%GECLO    )) ALLOCATE (X1_%GECLO       (SIZE (X1) * SIZE (X1 (1)%GECLO     )))
IF (ASSOCIATED (X1 (1)%GESLO    )) ALLOCATE (X1_%GESLO       (SIZE (X1) * SIZE (X1 (1)%GESLO     )))
IF (ASSOCIATED (X1 (1)%GM       )) ALLOCATE (X1_%GM          (SIZE (X1) * SIZE (X1 (1)%GM        )))
IF (ASSOCIATED (X1 (1)%GMAPPA   )) ALLOCATE (X1_%GMAPPA      (SIZE (X1) * SIZE (X1 (1)%GMAPPA    )))
IF (ASSOCIATED (X1 (1)%GOMVRL   )) ALLOCATE (X1_%GOMVRL      (SIZE (X1) * SIZE (X1 (1)%GOMVRL    )))
IF (ASSOCIATED (X1 (1)%GOMVRM   )) ALLOCATE (X1_%GOMVRM      (SIZE (X1) * SIZE (X1 (1)%GOMVRM    )))
IF (ASSOCIATED (X1 (1)%GNORDL   )) ALLOCATE (X1_%GNORDL      (SIZE (X1) * SIZE (X1 (1)%GNORDL    )))
IF (ASSOCIATED (X1 (1)%GNORDM   )) ALLOCATE (X1_%GNORDM      (SIZE (X1) * SIZE (X1 (1)%GNORDM    )))
IF (ASSOCIATED (X1 (1)%GNORDLCL )) ALLOCATE (X1_%GNORDLCL    (SIZE (X1) * SIZE (X1 (1)%GNORDLCL  )))
IF (ASSOCIATED (X1 (1)%GNORDMCL )) ALLOCATE (X1_%GNORDMCL    (SIZE (X1) * SIZE (X1 (1)%GNORDMCL  )))
IF (ASSOCIATED (X1 (1)%GNORDMCM )) ALLOCATE (X1_%GNORDMCM    (SIZE (X1) * SIZE (X1 (1)%GNORDMCM  )))
IF (ASSOCIATED (X1 (1)%GAW      )) ALLOCATE (X1_%GAW         (SIZE (X1) * SIZE (X1 (1)%GAW       )))
IF (ASSOCIATED (X1 (1)%NGPLAT   )) ALLOCATE (X1_%NGPLAT      (SIZE (X1) * SIZE (X1 (1)%NGPLAT    )))
IF (ASSOCIATED (X1 (1)%NUNIQUEGP)) ALLOCATE (X1_%NUNIQUEGP   (SIZE (X1) * SIZE (X1 (1)%NUNIQUEGP )))

END SUBROUTINE


END 
