INTERFACE
SUBROUTINE GPRCP(KLON,KIDIA,KFDIA,KFLEV,PQ,PQI,PQL,PQR,PQS,PQG,&
 & PCP,PR,PKAP,PGFL,KGFLTYP)
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMCST   , ONLY : RD, RV, RCPD, RCPV, RCW, RCS
USE YOM_YGFL , ONLY : YGFL
IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(IN)    :: KLON
INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLEV
REAL(KIND=JPRB),OPTIONAL   ,INTENT(IN)    :: PQ(KLON,KFLEV)
REAL(KIND=JPRB),OPTIONAL   ,INTENT(IN)    :: PQI(KLON,KFLEV)
REAL(KIND=JPRB),OPTIONAL   ,INTENT(IN)    :: PQL(KLON,KFLEV)
REAL(KIND=JPRB),OPTIONAL   ,INTENT(IN)    :: PQR(KLON,KFLEV)
REAL(KIND=JPRB),OPTIONAL   ,INTENT(IN)    :: PQS(KLON,KFLEV)
REAL(KIND=JPRB),OPTIONAL   ,INTENT(IN)    :: PQG(KLON,KFLEV)
REAL(KIND=JPRB),OPTIONAL   ,INTENT(OUT)   :: PCP(KLON,KFLEV)
REAL(KIND=JPRB),OPTIONAL   ,INTENT(OUT)   :: PR(KLON,KFLEV)
REAL(KIND=JPRB),OPTIONAL   ,INTENT(OUT)   :: PKAP(KLON,KFLEV)
REAL(KIND=JPRB),OPTIONAL   ,INTENT(IN)    :: PGFL(KLON,KFLEV,YGFL%NDIM)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)    :: KGFLTYP
END SUBROUTINE GPRCP
END INTERFACE
