SUBROUTINE LACDYN_LOAD_ALL (CDNAME)

USE LOAD_MOD, ONLY : OPEN_LOAD, CLOSE_LOAD, ILUN_IN, LOAD

CHARACTER (LEN=*) :: CDNAME



! CALL OPEN_LOAD (CDNAME)
! CALL LOAD_INTDYN_MOD
! CALL LOAD_PAR_RDLR
  CALL LOAD_PTRSLB1

CONTAINS
SUBROUTINE LOAD_INTDYN_MOD
USE INTDYN_MOD
  CALL LOAD (ILUN_IN, YYTCTY0%M_EVEL)
  CALL LOAD (ILUN_IN, YYTCTY0%M_PSDVBC)
  CALL LOAD (ILUN_IN, YYTCTY0%NDIM)
!$acc enter data copyin (YYTCTY0)
  CALL LOAD (ILUN_IN, YYTHW0%NDIM)
!$acc enter data copyin (YYTHW0)
  CALL LOAD (ILUN_IN, YYTTND%M_TNDASRU)
  CALL LOAD (ILUN_IN, YYTTND%M_TNDASRV)
  CALL LOAD (ILUN_IN, YYTTND%M_TNDGW)
  CALL LOAD (ILUN_IN, YYTTND%M_TNDPD)
  CALL LOAD (ILUN_IN, YYTTND%M_TNDT)
  CALL LOAD (ILUN_IN, YYTTND%M_TNDU)
  CALL LOAD (ILUN_IN, YYTTND%M_TNDU_NOC)
  CALL LOAD (ILUN_IN, YYTTND%M_TNDV)
  CALL LOAD (ILUN_IN, YYTTND%M_TNDVD)
  CALL LOAD (ILUN_IN, YYTTND%M_TNDV_NOC)
  CALL LOAD (ILUN_IN, YYTTND%NDIM)
!$acc enter data copyin (YYTTND)
  CALL LOAD (ILUN_IN, YYTVC0%M_VCASRSF)
  CALL LOAD (ILUN_IN, YYTVC0%M_VCASRSH)
  CALL LOAD (ILUN_IN, YYTVC0%M_VCRSSAF)
  CALL LOAD (ILUN_IN, YYTVC0%NDIM)
!$acc enter data copyin (YYTVC0)
END SUBROUTINE
SUBROUTINE LOAD_PAR_RDLR
USE PAR_RDLR
  CALL LOAD (ILUN_IN, JP_ASRF)
  CALL LOAD (ILUN_IN, JP_DIMR0)
  CALL LOAD (ILUN_IN, JP_DIMR9)
  CALL LOAD (ILUN_IN, JP_RSAF)
!$acc enter data copyin (JP_ASRF)
!$acc enter data copyin (JP_DIMR0)
!$acc enter data copyin (JP_DIMR9)
!$acc enter data copyin (JP_RSAF)
END SUBROUTINE
SUBROUTINE LOAD_PTRSLB1
USE PTRSLB1

  YRPTRSLB1%NFLDSLB1 = 2713

  PRINT *, __FILE__//':', __LINE__
  PRINT *, YRPTRSLB1%NFLDSLB1

!$acc kernels
  PRINT *, YRPTRSLB1%NFLDSLB1
!$acc end kernels
  PRINT *, __FILE__//':', __LINE__


END SUBROUTINE

END SUBROUTINE LACDYN_LOAD_ALL
