SUBROUTINE LACDYN_LOAD_ALL (CDNAME)

USE LOAD_MOD, ONLY : OPEN_LOAD, CLOSE_LOAD, ILUN_IN, LOAD

CHARACTER (LEN=*) :: CDNAME



  CALL OPEN_LOAD (CDNAME)
  CALL LOAD_INTDYN_MOD
  CALL LOAD_PAR_RDLR
  CALL LOAD_PTRSLB1
  CALL LOAD_PTRSLB2
  CALL LOAD_YEMDYN
  CALL LOAD_YOEPHY
  CALL LOAD_YOMCST
  CALL LOAD_YOMCT0
  CALL LOAD_YOMCT3
  CALL LOAD_YOMCVER
  CALL LOAD_YOMDIM
  CALL LOAD_YOMDIMV
  CALL LOAD_YOMDYN
  CALL LOAD_YOMDYNA
  CALL LOAD_YOMGEM
  CALL LOAD_YOMLDDH
  CALL LOAD_YOMMDDH
  CALL LOAD_YOMPARAR
  CALL LOAD_YOMPHY
  CALL LOAD_YOMSTA
  CALL LOAD_YOMVERT
  CALL LOAD_YOM_YGFL
  CALL CLOSE_LOAD



CONTAINS
SUBROUTINE LOAD_INTDYN_MOD
USE INTDYN_MOD
  CALL LOAD (ILUN_IN, YYTCTY0%M_EVEL)
  CALL LOAD (ILUN_IN, YYTCTY0%M_PSDVBC)
  CALL LOAD (ILUN_IN, YYTCTY0%NDIM)
!$acc enter data copyin (YYTCTY0)
  CALL LOAD (ILUN_IN, YYTHW0%NDIM)
!$acc enter data copyin (YYTHW0)
  CALL LOAD (ILUN_IN, YYTTND%M_TNDASRU)
  CALL LOAD (ILUN_IN, YYTTND%M_TNDASRV)
  CALL LOAD (ILUN_IN, YYTTND%M_TNDGW)
  CALL LOAD (ILUN_IN, YYTTND%M_TNDPD)
  CALL LOAD (ILUN_IN, YYTTND%M_TNDT)
  CALL LOAD (ILUN_IN, YYTTND%M_TNDU)
  CALL LOAD (ILUN_IN, YYTTND%M_TNDU_NOC)
  CALL LOAD (ILUN_IN, YYTTND%M_TNDV)
  CALL LOAD (ILUN_IN, YYTTND%M_TNDVD)
  CALL LOAD (ILUN_IN, YYTTND%M_TNDV_NOC)
  CALL LOAD (ILUN_IN, YYTTND%NDIM)
!$acc enter data copyin (YYTTND)
  CALL LOAD (ILUN_IN, YYTVC0%M_VCASRSF)
  CALL LOAD (ILUN_IN, YYTVC0%M_VCASRSH)
  CALL LOAD (ILUN_IN, YYTVC0%M_VCRSSAF)
  CALL LOAD (ILUN_IN, YYTVC0%NDIM)
!$acc enter data copyin (YYTVC0)
END SUBROUTINE
SUBROUTINE LOAD_PAR_RDLR
USE PAR_RDLR
  CALL LOAD (ILUN_IN, JP_ASRF)
  CALL LOAD (ILUN_IN, JP_DIMR0)
  CALL LOAD (ILUN_IN, JP_DIMR9)
  CALL LOAD (ILUN_IN, JP_RSAF)
!$acc enter data copyin (JP_ASRF)
!$acc enter data copyin (JP_DIMR0)
!$acc enter data copyin (JP_DIMR9)
!$acc enter data copyin (JP_RSAF)
END SUBROUTINE
SUBROUTINE LOAD_PTRSLB1
USE PTRSLB1
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1C9)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1C9_SI)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1GFL9)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1GFLF9)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1GFLP9)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1NHX9)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1PD0)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1PD9)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1PD9_SI)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1RSSA9)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1SP9)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1T0)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1T9)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1T9_SI)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1TF9)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1TP9)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1U0)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1U9)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1U9_SI)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1UF9)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1UP9)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1UR0)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1UR9)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1V0)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1V9)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1V9_SI)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1VD0)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1VD9)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1VD9_SI)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1VDF9)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1VF9)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1VP9)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1VR0)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1VR9)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1WR0)
  CALL LOAD (ILUN_IN, YRPTRSLB1%MSLB1WRA)
  CALL LOAD (ILUN_IN, YRPTRSLB1%NFLDSLB1)
!$acc enter data copyin (YRPTRSLB1)

  PRINT *, __FILE__//':', __LINE__
  PRINT *, YRPTRSLB1%NFLDSLB1

!$acc kernels
  PRINT *, YRPTRSLB1%NFLDSLB1
!$acc end kernels
  PRINT *, __FILE__//':', __LINE__


END SUBROUTINE
SUBROUTINE LOAD_PTRSLB2
USE PTRSLB2
  CALL LOAD (ILUN_IN, YRPTRSLB2%MSLB2PDSI)
  CALL LOAD (ILUN_IN, YRPTRSLB2%MSLB2SPSI)
  CALL LOAD (ILUN_IN, YRPTRSLB2%MSLB2TSI)
  CALL LOAD (ILUN_IN, YRPTRSLB2%MSLB2URL)
  CALL LOAD (ILUN_IN, YRPTRSLB2%MSLB2USI)
  CALL LOAD (ILUN_IN, YRPTRSLB2%MSLB2VCVWEI)
  CALL LOAD (ILUN_IN, YRPTRSLB2%MSLB2VDSI)
  CALL LOAD (ILUN_IN, YRPTRSLB2%MSLB2VRL)
  CALL LOAD (ILUN_IN, YRPTRSLB2%MSLB2VSI)
  CALL LOAD (ILUN_IN, YRPTRSLB2%MSLB2WRL)
  CALL LOAD (ILUN_IN, YRPTRSLB2%NFLDSLB2)
!$acc enter data copyin (YRPTRSLB2)
END SUBROUTINE
SUBROUTINE LOAD_YEMDYN
USE YEMDYN
  CALL LOAD (ILUN_IN, YREDYN%LESIDG)
!$acc enter data copyin (YREDYN)
END SUBROUTINE
SUBROUTINE LOAD_YOEPHY
USE YOEPHY
  CALL LOAD (ILUN_IN, YREPHY%LAGPHY)
  CALL LOAD (ILUN_IN, YREPHY%LEPHYS)
!$acc enter data copyin (YREPHY)
END SUBROUTINE
SUBROUTINE LOAD_YOMCST
USE YOMCST
  CALL LOAD (ILUN_IN, RA)
  CALL LOAD (ILUN_IN, RCPD)
  CALL LOAD (ILUN_IN, RCPV)
  CALL LOAD (ILUN_IN, RCS)
  CALL LOAD (ILUN_IN, RCW)
  CALL LOAD (ILUN_IN, RD)
  CALL LOAD (ILUN_IN, RKAPPA)
  CALL LOAD (ILUN_IN, RV)
!$acc enter data copyin (RA)
!$acc enter data copyin (RCPD)
!$acc enter data copyin (RCPV)
!$acc enter data copyin (RCS)
!$acc enter data copyin (RCW)
!$acc enter data copyin (RD)
!$acc enter data copyin (RKAPPA)
!$acc enter data copyin (RV)
END SUBROUTINE
SUBROUTINE LOAD_YOMCT0
USE YOMCT0
  CALL LOAD (ILUN_IN, LAROME)
  CALL LOAD (ILUN_IN, LNHDYN)
  CALL LOAD (ILUN_IN, LSLPHY)
  CALL LOAD (ILUN_IN, LSPRT)
  CALL LOAD (ILUN_IN, LTWOTL)
!$acc enter data copyin (LAROME)
!$acc enter data copyin (LNHDYN)
!$acc enter data copyin (LSLPHY)
!$acc enter data copyin (LSPRT)
!$acc enter data copyin (LTWOTL)
END SUBROUTINE
SUBROUTINE LOAD_YOMCT3
USE YOMCT3
  CALL LOAD (ILUN_IN, NSTEP)
!$acc enter data copyin (NSTEP)
END SUBROUTINE
SUBROUTINE LOAD_YOMCVER
USE YOMCVER
  CALL LOAD (ILUN_IN, LRNHC1)
  CALL LOAD (ILUN_IN, LVERTFE)
  CALL LOAD (ILUN_IN, LVFE_INTB)
!$acc enter data copyin (LRNHC1)
!$acc enter data copyin (LVERTFE)
!$acc enter data copyin (LVFE_INTB)
END SUBROUTINE
SUBROUTINE LOAD_YOMDIM
USE YOMDIM
  CALL LOAD (ILUN_IN, YRDIM%NPROMA)
  CALL LOAD (ILUN_IN, YRDIM%NPROMDLR)
  CALL LOAD (ILUN_IN, YRDIM%NPROMDLW)
  CALL LOAD (ILUN_IN, YRDIM%NPROMNH)
  CALL LOAD (ILUN_IN, YRDIM%NPROMVC)
!$acc enter data copyin (YRDIM)
END SUBROUTINE
SUBROUTINE LOAD_YOMDIMV
USE YOMDIMV
  CALL LOAD (ILUN_IN, YRDIMV%NFLEN)
  CALL LOAD (ILUN_IN, YRDIMV%NFLEVG)
  CALL LOAD (ILUN_IN, YRDIMV%NFLSA)
!$acc enter data copyin (YRDIMV)
END SUBROUTINE
SUBROUTINE LOAD_YOMDYN
USE YOMDYN
  CALL LOAD (ILUN_IN, YRDYN%L2TLFF)
  CALL LOAD (ILUN_IN, YRDYN%LADVF)
  CALL LOAD (ILUN_IN, YRDYN%LADVFW)
  CALL LOAD (ILUN_IN, YRDYN%LIMPF)
  CALL LOAD (ILUN_IN, YRDYN%LSETFSTAT)
  CALL LOAD (ILUN_IN, YRDYN%LSETTLSVF)
  CALL LOAD (ILUN_IN, YRDYN%LSIDG)
  CALL LOAD (ILUN_IN, YRDYN%LSPLTHOIGFL)
  CALL LOAD (ILUN_IN, YRDYN%LSVTSM)
  CALL LOAD (ILUN_IN, YRDYN%NCURRENT_ITER)
  CALL LOAD (ILUN_IN, YRDYN%NFLEVSF)
  CALL LOAD (ILUN_IN, YRDYN%NSPDLAG)
  CALL LOAD (ILUN_IN, YRDYN%NSPLTHOI)
  CALL LOAD (ILUN_IN, YRDYN%NSVDLAG)
  CALL LOAD (ILUN_IN, YRDYN%NTLAG)
  CALL LOAD (ILUN_IN, YRDYN%NVLAG)
  CALL LOAD (ILUN_IN, YRDYN%NWLAG)
  CALL LOAD (ILUN_IN, YRDYN%RCMSLP0)
  CALL LOAD (ILUN_IN, YRDYN%RCORDIF)
  CALL LOAD (ILUN_IN, YRDYN%RCORDIH)
  CALL LOAD (ILUN_IN, YRDYN%REPSDYN)
  CALL LOAD (ILUN_IN, YRDYN%RSETTLF)
  CALL LOAD (ILUN_IN, YRDYN%SIALPH)
  CALL LOAD (ILUN_IN, YRDYN%SIDELP)
  CALL LOAD (ILUN_IN, YRDYN%SILNPR)
  CALL LOAD (ILUN_IN, YRDYN%SIRPRG)
  CALL LOAD (ILUN_IN, YRDYN%SIRDEL)
  CALL LOAD (ILUN_IN, YRDYN%SIRPRN)
  CALL LOAD (ILUN_IN, YRDYN%SITR)
  CALL LOAD (ILUN_IN, YRDYN%VESL)
  CALL LOAD (ILUN_IN, YRDYN%XIDT)
!$acc enter data copyin (YRDYN)
END SUBROUTINE
SUBROUTINE LOAD_YOMDYNA
USE YOMDYNA
  CALL LOAD (ILUN_IN, LCOMAD)
!$acc enter data copyin (LCOMAD)
  CALL LOAD (ILUN_IN, LCOMADH)
!$acc enter data copyin (LCOMADH)
  CALL LOAD (ILUN_IN, LCOMADV)
!$acc enter data copyin (LCOMADV)
  CALL LOAD (ILUN_IN, LELTRA)
!$acc enter data copyin (LELTRA)
  CALL LOAD (ILUN_IN, LGWADV)
!$acc enter data copyin (LGWADV)
  CALL LOAD (ILUN_IN, LNESC)
!$acc enter data copyin (LNESC)
  CALL LOAD (ILUN_IN, LNESCT)
!$acc enter data copyin (LNESCT)
  CALL LOAD (ILUN_IN, LNESCV)
!$acc enter data copyin (LNESCV)
  CALL LOAD (ILUN_IN, LNH_GEOGW)
!$acc enter data copyin (LNH_GEOGW)
  CALL LOAD (ILUN_IN, LNH_PDVD)
!$acc enter data copyin (LNH_PDVD)
  CALL LOAD (ILUN_IN, LPC_CHEAP)
!$acc enter data copyin (LPC_CHEAP)
  CALL LOAD (ILUN_IN, LPC_FULL)
!$acc enter data copyin (LPC_FULL)
  CALL LOAD (ILUN_IN, LRDBBC)
!$acc enter data copyin (LRDBBC)
  CALL LOAD (ILUN_IN, LRWSDLR)
!$acc enter data copyin (LRWSDLR)
  CALL LOAD (ILUN_IN, LRWSDLW)
!$acc enter data copyin (LRWSDLW)
  CALL LOAD (ILUN_IN, LSETTLS)
!$acc enter data copyin (LSETTLS)
  CALL LOAD (ILUN_IN, LSETTLST)
!$acc enter data copyin (LSETTLST)
  CALL LOAD (ILUN_IN, LSETTLSV)
!$acc enter data copyin (LSETTLSV)
  CALL LOAD (ILUN_IN, LSLHD)
!$acc enter data copyin (LSLHD)
  CALL LOAD (ILUN_IN, LSLINL)
!$acc enter data copyin (LSLINL)
  CALL LOAD (ILUN_IN, LSLINLC1)
!$acc enter data copyin (LSLINLC1)
  CALL LOAD (ILUN_IN, LSLINLC2)
!$acc enter data copyin (LSLINLC2)
  CALL LOAD (ILUN_IN, LVERCOR)
!$acc enter data copyin (LVERCOR)
  CALL LOAD (ILUN_IN, ND4SYS)
!$acc enter data copyin (ND4SYS)
  CALL LOAD (ILUN_IN, NPDVAR)
!$acc enter data copyin (NPDVAR)
  CALL LOAD (ILUN_IN, NVDVAR)
!$acc enter data copyin (NVDVAR)
END SUBROUTINE
SUBROUTINE LOAD_YOMGEM
USE YOMGEM
  CALL LOAD (ILUN_IN, YRGEM%RSTRET)
!$acc enter data copyin (YRGEM)
END SUBROUTINE
SUBROUTINE LOAD_YOMLDDH
USE YOMLDDH
  CALL LOAD (ILUN_IN, YRLDDH%LRSIDDH)
!$acc enter data copyin (YRLDDH)
END SUBROUTINE
SUBROUTINE LOAD_YOMMDDH
USE YOMMDDH
  CALL LOAD (ILUN_IN, YRMDDH%MSIDDH_PD0)
  CALL LOAD (ILUN_IN, YRMDDH%MSIDDH_PD9)
  CALL LOAD (ILUN_IN, YRMDDH%MSIDDH_T0)
  CALL LOAD (ILUN_IN, YRMDDH%MSIDDH_T9)
  CALL LOAD (ILUN_IN, YRMDDH%MSIDDH_U0)
  CALL LOAD (ILUN_IN, YRMDDH%MSIDDH_U9)
  CALL LOAD (ILUN_IN, YRMDDH%MSIDDH_V0)
  CALL LOAD (ILUN_IN, YRMDDH%MSIDDH_V9)
  CALL LOAD (ILUN_IN, YRMDDH%MSIDDH_VD0)
  CALL LOAD (ILUN_IN, YRMDDH%MSIDDH_VD9)
  CALL LOAD (ILUN_IN, YRMDDH%NDIMSIGMV)
!$acc enter data copyin (YRMDDH)
END SUBROUTINE
SUBROUTINE LOAD_YOMPARAR
USE YOMPARAR
  CALL LOAD (ILUN_IN, YRPARAR%LSQUALL)
  CALL LOAD (ILUN_IN, YRPARAR%VSQUALL)
!$acc enter data copyin (YRPARAR)
END SUBROUTINE
SUBROUTINE LOAD_YOMPHY
USE YOMPHY
  CALL LOAD (ILUN_IN, YRPHY%LMPHYS)
!$acc enter data copyin (YRPHY)
END SUBROUTINE
SUBROUTINE LOAD_YOMSTA
USE YOMSTA
  CALL LOAD (ILUN_IN, YRSTA%RTSUR)
!$acc enter data copyin (YRSTA)
!$acc enter data copyin (YRSTA%STPREH)
!$acc enter data copyin (YRSTA%STPRE)
!$acc enter data copyin (YRSTA%STPHI)
!$acc enter data copyin (YRSTA%STTEM)
!$acc enter data copyin (YRSTA%STDEN)
!$acc enter data copyin (YRSTA%STZ)
END SUBROUTINE
SUBROUTINE LOAD_YOMVERT
USE YOMVERT
  CALL LOAD (ILUN_IN, YRVAB%VBF        )
  CALL LOAD (ILUN_IN, YRVAB%VBH        )
  CALL LOAD (ILUN_IN, YRVAB%VDELB      )
!$acc enter data copyin (YRVAB)
  CALL LOAD (ILUN_IN, YRVETA%VETAH     )
  CALL LOAD (ILUN_IN, YRVETA%VFE_RDETAH)
!$acc enter data copyin (YRVETA)
  CALL LOAD (ILUN_IN, YRVFE%RINTBF11   )
  CALL LOAD (ILUN_IN, YRVFE%RINTE      )
!$acc enter data copyin (YRVFE)
END SUBROUTINE
SUBROUTINE LOAD_YOM_YGFL
USE YOM_YGFL
  CALL LOAD (ILUN_IN, YGFL%NDIM)
  CALL LOAD (ILUN_IN, YGFL%NUMFLDS)
  CALL LOAD (ILUN_IN, YGFL%YCOMP)
  CALL LOAD (ILUN_IN, YGFL%YCVGQ%LGP)
  CALL LOAD (ILUN_IN, YGFL%YCVGQ%LTDIABLIN)
  CALL LOAD (ILUN_IN, YGFL%YCVGQ%MP_SL1)
  CALL LOAD (ILUN_IN, YGFL%YG%LTHERMACT)
  CALL LOAD (ILUN_IN, YGFL%YI%LTHERMACT)
  CALL LOAD (ILUN_IN, YGFL%YL%LTHERMACT)
  CALL LOAD (ILUN_IN, YGFL%YQ%LTDIABLIN)
  CALL LOAD (ILUN_IN, YGFL%YQ%LTHERMACT)
  CALL LOAD (ILUN_IN, YGFL%YQ%MP_SL1)
  CALL LOAD (ILUN_IN, YGFL%YR%LTHERMACT)
  CALL LOAD (ILUN_IN, YGFL%YS%LTHERMACT)
!$acc enter data copyin (YGFL)
!$acc enter data copyin (YGFL%YCOMP)
END SUBROUTINE
END SUBROUTINE LACDYN_LOAD_ALL
