INTERFACE
SUBROUTINE LACDYN(YDGMV, &
 ! --- INPUT ------------------------------------------------------------------
 & KST,KPROF,PBETADT,PDT,PSLHDA,PSLHDD0, &
 & YDGSGEOM,YDOROG,POROGL,POROGM,&
 & PVCRSSA9F,PNHXT9,PVCRS0,PVCW0F,PWDLW0F,PRDLR0,PRDLR9,PNHXT0,&
 & PRES0,PRDELP0,PCTY0,PUVH0,&
 & PATND,PDBBC,PRDPHI,PGWT0,PGWT9,PGFL,&
 ! --- INPUT/OUTPUT -----------------------------------------------------------
 & KSETTLOFF,PGMV,PGMVS,PB1,PB2,PGMVT1,PGMVT1S,PGWS,PGMVTNDSI,PWRL95)
USE YOMGMV   , ONLY : TGMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDIM   , ONLY : YRDIM
USE YOMDIMV  , ONLY : YRDIMV
USE YOMDYNA  , ONLY : LGWADV, LRDBBC, LSLHD, LNH_PDVD, LNH_GEOGW,&
                    & LCOMAD, LCOMADH, LCOMADV, LPC_FULL, LPC_CHEAP
USE YOMDYN   , ONLY : YRDYN
USE YOM_YGFL , ONLY : YGFL
USE PAR_RDLR , ONLY : JP_DIMR0, JP_DIMR9
USE YOMMDDH  , ONLY : YRMDDH
USE YOMGSGEOM, ONLY : TGSGEOM
USE YOMOROG  , ONLY : TOROG
USE INTDYN_MOD,ONLY : YYTVC0, YYTTND, YYTHW0, YYTCTY0
USE PTRSLB1  , ONLY : YRPTRSLB1
USE PTRSLB2  , ONLY : YRPTRSLB2
IMPLICIT NONE
TYPE(TGMV) , INTENT(INOUT) :: YDGMV
INTEGER(KIND=JPIM),INTENT(IN)    :: KST
INTEGER(KIND=JPIM),INTENT(IN)    :: KPROF
REAL(KIND=JPRB)   ,INTENT(IN)    :: PBETADT
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDT
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSLHDA(YRDIM%NPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSLHDD0(YRDIM%NPROMA)
TYPE(TGSGEOM)     ,INTENT(IN)    :: YDGSGEOM
TYPE(TOROG)       ,INTENT(IN)    :: YDOROG
REAL(KIND=JPRB)   ,INTENT(IN)    :: POROGL(YRDIM%NPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)    :: POROGM(YRDIM%NPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PVCRSSA9F(YRDIM%NPROMVC,YRDIMV%NFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PNHXT9(YRDIM%NPROMA,YRDIMV%NFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PVCRS0(YRDIM%NPROMVC,0:YRDIMV%NFLEVG,YYTVC0%NDIM)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PVCW0F(YRDIM%NPROMVC,YRDIMV%NFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PWDLW0F(YRDIM%NPROMDLW,YRDIMV%NFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRDLR0(YRDIM%NPROMDLR,0:YRDIMV%NFLEVG,JP_DIMR0)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRDLR9(YRDIM%NPROMDLR,0:YRDIMV%NFLEVG,JP_DIMR9)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PNHXT0(YRDIM%NPROMA,YRDIMV%NFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRES0(YRDIM%NPROMA,0:YRDIMV%NFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRDELP0(YRDIM%NPROMA,YRDIMV%NFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCTY0(YRDIM%NPROMA,0:YRDIMV%NFLEVG,YYTCTY0%NDIM)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PUVH0(YRDIM%NPROMA,0:YRDIMV%NFLEVG,YYTHW0%NDIM)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PATND(YRDIM%NPROMA,YRDIMV%NFLEVG,YYTTND%NDIM)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDBBC(YRDIM%NPROMNH)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRDPHI(YRDIM%NPROMNH,YRDIMV%NFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGWT0(YRDIM%NPROMNH,YRDIMV%NFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGWT9(YRDIM%NPROMNH,YRDIMV%NFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGFL(YRDIM%NPROMA,YRDIMV%NFLEVG,YGFL%NDIM)
INTEGER(KIND=JPIM),INTENT(OUT)   :: KSETTLOFF(YRDIMV%NFLEVG)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGMV(YRDIM%NPROMA,YRDIMV%NFLEVG,YDGMV%NDIMGMV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGMVS(YRDIM%NPROMA,YDGMV%NDIMGMVS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PB1(YRDIM%NPROMA,YRPTRSLB1%NFLDSLB1)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PB2(YRDIM%NPROMA,YRPTRSLB2%NFLDSLB2)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGMVT1(YRDIM%NPROMA,YRDIMV%NFLEVG,YDGMV%YT1%NDIM)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGMVT1S(YRDIM%NPROMA,YDGMV%YT1%NDIMS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGWS(YRDIM%NPROMNH)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGMVTNDSI(YRDIM%NPROMA,YRDIMV%NFLEVG,YRMDDH%NDIMSIGMV)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PWRL95(YRDIM%NPROMA,YRDIMV%NFLEVG)
END SUBROUTINE LACDYN
END INTERFACE
