INTERFACE
SUBROUTINE LASURE(&
 ! ----- INPUT ---------------------------------------------------------------
 & KSTART,KPROF,PBETADT,PDT,YDGSGEOM,&
 ! ----- OUTPUT --------------------------------------------------------------
 & PDTS2,PBT,LD2TLFF1,PBDT,PREDIV,PESGP,PESGM )
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOEPHY   , ONLY : YREPHY
USE YOMPHY   , ONLY : YRPHY
USE YOMDIM   , ONLY : YRDIM
USE YEMDYN   , ONLY : YREDYN
USE YOMDYN   , ONLY : YRDYN
USE YOMGEM   , ONLY : YRGEM
USE YOMGSGEOM, ONLY : TGSGEOM
IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTART
INTEGER(KIND=JPIM),INTENT(IN)    :: KPROF
REAL(KIND=JPRB)   ,INTENT(IN)    :: PBETADT
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDT
TYPE(TGSGEOM)     ,INTENT(IN)    :: YDGSGEOM
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PDTS2
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PBT
LOGICAL           ,INTENT(OUT)   :: LD2TLFF1
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PBDT(YRDIM%NPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PREDIV(YRDIM%NPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PESGP
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PESGM
END SUBROUTINE LASURE
END INTERFACE
