INTERFACE
SUBROUTINE LASURE(&
 
 & KLON, KIDIA,KFDIA,PBETADT,PDT,YDGSGEOM,&
 
 & PDTS2,PBT,LD2TLFF1,PBDT,PREDIV,PESGP,PESGM,KSTPT,KSTSZ,PSTACK )  

USE PARKIND1 , ONLY : JPIM, JPRB

USE YOEPHY   , ONLY : YREPHY
USE YOMPHY   , ONLY : YRPHY
USE YOMDIM   , ONLY : YRDIM
USE YEMDYN   , ONLY : YREDYN
USE YOMDYN   , ONLY : YRDYN
USE YOMGEM   , ONLY : YRGEM
USE YOMGSGEOM, ONLY : TGSGEOM

INTEGER(KIND=JPIM),INTENT(IN)    :: KLON
INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PBETADT
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDT 
TYPE(TGSGEOM)     ,INTENT(IN)    :: YDGSGEOM
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PDTS2 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PBT 
LOGICAL           ,INTENT(OUT)   :: LD2TLFF1 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PBDT(KLON) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PREDIV(KLON) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PESGP 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PESGM 

INTEGER(KIND=JPIM),INTENT(IN)    :: KSTSZ
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTPT
REAL (KIND=JPRB)   ,INTENT(INOUT) :: PSTACK (KSTSZ)

END SUBROUTINE LASURE

END INTERFACE
