INTERFACE
SUBROUTINE LATTES(YDGMV,KST,KPROF,PDTS2,PBDT,PESGP,PESGM,&
 & PVCRS0,PRDLR0,YDOROG,POROGL,POROGM,&
 & PSDIV0,PSDIV9,PSDVBC,PRES0,PGMVS,&
 & PGMV,PGMVT1S,PB1,PB2)
USE YOMGMV   , ONLY : TGMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMCST   , ONLY : RD
USE YOMCT0   , ONLY : LTWOTL
USE YOMCT3   , ONLY : NSTEP
USE YOMCVER  , ONLY : LVERTFE, LVFE_INTB
USE YOMDIM   , ONLY : YRDIM
USE YOMDIMV  , ONLY : YRDIMV
USE YOMVERT  , ONLY : YRVAB, YRVETA, YRVFE
USE YOMOROG  , ONLY : TOROG
USE YOMDYNA  , ONLY : LVERCOR, LRWSDLR, LPC_FULL, LPC_CHEAP, LNESC, LSETTLS, LSLINLC1
USE YOMDYN   , ONLY : YRDYN
USE YOMSTA   , ONLY : YRSTA
USE PTRSLB1  , ONLY : YRPTRSLB1
USE PTRSLB2  , ONLY : YRPTRSLB2
USE PAR_RDLR , ONLY : JP_ASRF, JP_DIMR0
USE INTDYN_MOD,ONLY : YYTVC0
IMPLICIT NONE
TYPE(TGMV) , INTENT(INOUT) :: YDGMV
INTEGER(KIND=JPIM),INTENT(IN)    :: KST
INTEGER(KIND=JPIM),INTENT(IN)    :: KPROF
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDTS2
REAL(KIND=JPRB)   ,INTENT(IN)    :: PBDT(YRDIM%NPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PESGP
REAL(KIND=JPRB)   ,INTENT(IN)    :: PESGM
REAL(KIND=JPRB)   ,INTENT(IN)    :: PVCRS0(YRDIM%NPROMVC,0:YRDIMV%NFLEVG,YYTVC0%NDIM)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRDLR0(YRDIM%NPROMDLR,0:YRDIMV%NFLEVG,JP_DIMR0)
TYPE(TOROG)       ,INTENT(IN)    :: YDOROG
REAL(KIND=JPRB)   ,INTENT(IN)    :: POROGL(YRDIM%NPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)    :: POROGM(YRDIM%NPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSDIV0(YRDIM%NPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSDIV9(YRDIM%NPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSDVBC(YRDIM%NPROMA,0:YRDIMV%NFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRES0(YRDIM%NPROMA,0:YRDIMV%NFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGMVS(YRDIM%NPROMA,YDGMV%NDIMGMVS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGMV(YRDIM%NPROMA,YRDIMV%NFLEVG,YDGMV%NDIMGMV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGMVT1S(YRDIM%NPROMA,YDGMV%YT1%NDIMS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PB1(YRDIM%NPROMA,YRPTRSLB1%NFLDSLB1)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PB2(YRDIM%NPROMA,YRPTRSLB2%NFLDSLB2)
END SUBROUTINE LATTES
END INTERFACE
