INTERFACE
SUBROUTINE LAVABO(KIDIA,KFDIA,LD2TLFF1,PB1)
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMCT0   , ONLY : LNHDYN, LSLPHY
USE YOMDIM   , ONLY : YRDIM
USE YOMDIMV  , ONLY : YRDIMV
USE YOMDYNA  , ONLY : LVERCOR, LRWSDLR, LRWSDLW, NVDVAR, LSLINL, LSLINLC1, LSLINLC2
USE YOMDYN   , ONLY : YRDYN
USE PTRSLB1  , ONLY : YRPTRSLB1
USE YOM_YGFL , ONLY : YGFL
IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA
LOGICAL           ,INTENT(IN)    :: LD2TLFF1
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PB1(YRDIM%NPROMA,YRPTRSLB1%NFLDSLB1)
END SUBROUTINE LAVABO
END INTERFACE
