INTERFACE
SUBROUTINE LAVENT(YDGMV,KIDIA,KFDIA,KSETTLOFF,LD2TLFF1,PVCRS0,PRDLR0,PDTS2,PRDELP,PEVEL,PATND,&
 & PGMV,PB1,PB2,PWRL9)
USE YOMGMV   , ONLY : TGMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMCST   , ONLY : RA
USE YOMCT0   , ONLY : LAROME, LTWOTL
USE YOMCT3   , ONLY : NSTEP
USE YOMCVER  , ONLY : LVERTFE
USE YOMDIM   , ONLY : YRDIM
USE YOMDIMV  , ONLY : YRDIMV
USE YOMDYNA  , ONLY : LVERCOR, LRWSDLR, LPC_FULL, LNESCT, LNESCV, LELTRA, LSETTLST, LSETTLSV
USE YOMDYN   , ONLY : YRDYN
USE YOMVERT  , ONLY : YRVETA
USE YOMPARAR , ONLY : YRPARAR
USE PTRSLB1  , ONLY : YRPTRSLB1
USE PTRSLB2  , ONLY : YRPTRSLB2
USE PAR_RDLR , ONLY : JP_ASRF, JP_DIMR0
USE INTDYN_MOD,ONLY : YYTVC0, YYTTND
IMPLICIT NONE
TYPE(TGMV) , INTENT(INOUT) :: YDGMV
INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA
INTEGER(KIND=JPIM),INTENT(OUT)   :: KSETTLOFF(YRDIMV%NFLEVG)
LOGICAL           ,INTENT(IN)    :: LD2TLFF1
REAL(KIND=JPRB)   ,INTENT(IN)    :: PVCRS0(YRDIM%NPROMVC,0:YRDIMV%NFLEVG,YYTVC0%NDIM)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRDLR0(YRDIM%NPROMDLR,0:YRDIMV%NFLEVG,JP_DIMR0)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDTS2
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRDELP(YRDIM%NPROMA,YRDIMV%NFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PEVEL(YRDIM%NPROMA,0:YRDIMV%NFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PATND(YRDIM%NPROMA,YRDIMV%NFLEVG,YYTTND%NDIM)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGMV(YRDIM%NPROMA,YRDIMV%NFLEVG,YDGMV%NDIMGMV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PB1(YRDIM%NPROMA,YRPTRSLB1%NFLDSLB1)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PB2(YRDIM%NPROMA,YRPTRSLB2%NFLDSLB2)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PWRL9(YRDIM%NPROMA,YRDIMV%NFLEVG)
END SUBROUTINE LAVENT
END INTERFACE
