MODULE LOAD_MOD

USE PARKIND1, ONLY : JPIM, JPRB

IMPLICIT NONE

INTERFACE LOAD
MODULE PROCEDURE LOADX0
MODULE PROCEDURE LOADX1
MODULE PROCEDURE LOADX2
MODULE PROCEDURE LOADX3
MODULE PROCEDURE LOADI0
MODULE PROCEDURE LOADI1
MODULE PROCEDURE LOADI2
MODULE PROCEDURE LOADI3
MODULE PROCEDURE LOADL0
MODULE PROCEDURE LOADC0
MODULE PROCEDURE LOAD_TYPE_GFL_COMP0
MODULE PROCEDURE LOAD_TYPE_GFL_COMP1
MODULE PROCEDURE LOAD_TGMV
MODULE PROCEDURE LOAD_TGSGEOM
MODULE PROCEDURE LOAD_TOROG
END INTERFACE LOAD

INTERFACE DIFF
MODULE PROCEDURE DIFFX0
MODULE PROCEDURE DIFFX1
MODULE PROCEDURE DIFFX2
MODULE PROCEDURE DIFFX3
MODULE PROCEDURE DIFFI0
MODULE PROCEDURE DIFFL0
MODULE PROCEDURE DIFFC0
END INTERFACE DIFF

INTEGER, PARAMETER :: ILUN_IN = 77, ILUN_OUT = 88, ILUNC = 99

CONTAINS

SUBROUTINE OPEN_LOAD (CDFILE)
CHARACTER (LEN=*) :: CDFILE

OPEN (ILUN_IN, FILE=TRIM (CDFILE)//'.IN', FORM="UNFORMATTED", ACTION="READ")
OPEN (ILUN_OUT, FILE=TRIM (CDFILE)//'.OUT', FORM="UNFORMATTED", ACTION="READ")
END SUBROUTINE OPEN_LOAD

SUBROUTINE CLOSE_LOAD
CLOSE (ILUN_IN)
CLOSE (ILUN_OUT)
END SUBROUTINE CLOSE_LOAD

SUBROUTINE DIFFX0 (CDNAME, X0, X0_1)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRB) :: X0, X0_1
IF (X0 /= X0_1) THEN
  WRITE (*, '(A32,12X,3E25.17)') CDNAME, X0, X0_1, X0_1 - X0
ENDIF
END SUBROUTINE DIFFX0

SUBROUTINE LOADX0 (ILUN, X0)
INTEGER          :: ILUN
REAL (KIND=JPRB) :: X0
READ (ILUN) X0
END SUBROUTINE LOADX0

SUBROUTINE DIFFX1 (CDNAME, X1, X1_1)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRB) :: X1 (:), X1_1 (:)
INTEGER :: I1
DO I1 = 1, SIZE (X1)
  IF (X1 (I1) /= X1_1 (I1)) THEN
    WRITE (*, '(A32,I12,12X,3E25.17)') CDNAME, I1, X1 (I1), X1_1 (I1), X1_1 (I1) - X1 (I1)
  ENDIF
ENDDO
END SUBROUTINE DIFFX1

SUBROUTINE LOADX1 (ILUN, X1)
INTEGER                   :: ILUN
REAL (KIND=JPRB), POINTER :: X1 (:)
INTEGER :: IL (1), IB (1)
READ (ILUN) IL
READ (ILUN) IB
ALLOCATE (X1 (IL (1): IB (1)))
READ (ILUN) X1
END SUBROUTINE LOADX1

SUBROUTINE DIFFX2 (CDNAME, X2, X2_1)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRB) :: X2 (:,:), X2_1 (:,:)
INTEGER :: I1, I2
DO I1 = 1, SIZE (X2, 1)
DO I2 = 1, SIZE (X2, 2)
  IF (X2 (I1, I2) /= X2_1 (I1, I2)) THEN
    WRITE (*, '(A32,I12,I12,3E25.17)') CDNAME, I1, I2, X2 (I1, I2), X2_1 (I1, I2), X2_1 (I1, I2) - X2 (I1, I2)
  ENDIF
ENDDO
ENDDO
END SUBROUTINE DIFFX2

SUBROUTINE DIFFX3 (CDNAME, X3, X3_1)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRB) :: X3 (:,:,:), X3_1 (:,:,:)
INTEGER :: I1, I2, I3
DO I1 = 1, SIZE (X3, 1)
DO I2 = 1, SIZE (X3, 2)
DO I3 = 1, SIZE (X3, 3)
  IF (X3 (I1, I2, I3) /= X3_1 (I1, I2, I3)) THEN
    WRITE (*, '(A32,I12,I12,I12,3E25.17)') CDNAME, I1, I2, I3, X3 (I1, I2, I3), X3_1 (I1, I2, I3), &
         & X3_1 (I1, I2, I3) - X3 (I1, I2, I3)
  ENDIF
ENDDO
ENDDO
ENDDO
END SUBROUTINE DIFFX3

SUBROUTINE LOADX2 (ILUN, X2)
INTEGER                   :: ILUN
REAL (KIND=JPRB), POINTER :: X2 (:,:)
INTEGER :: IL (2), IB (2)
READ (ILUN) IL
READ (ILUN) IB
ALLOCATE (X2 (IL (1): IB (1), IL (2): IB (2)))
READ (ILUN) X2
END SUBROUTINE LOADX2

SUBROUTINE LOADX3 (ILUN, X3)
INTEGER                   :: ILUN
REAL (KIND=JPRB), POINTER :: X3 (:,:,:)
INTEGER :: IL (3), IB (3)
READ (ILUN) IL
READ (ILUN) IB
ALLOCATE (X3 (IL (1): IB (1), IL (2): IB (2), IL (3): IB (3)))
READ (ILUN) X3
END SUBROUTINE LOADX3

SUBROUTINE DIFFI0 (CDNAME, I0, I0_1)
CHARACTER (LEN=*) :: CDNAME
INTEGER :: I0, I0_1
IF (I0 /= I0_1) THEN
  WRITE (*, '(A32,12X,12X,3I25)') CDNAME, I0, I0_1, I0-I0_1
ENDIF
END SUBROUTINE DIFFI0

SUBROUTINE LOADI0 (ILUN, I0)
INTEGER             :: ILUN
INTEGER (KIND=JPIM) :: I0
READ (ILUN) I0
END SUBROUTINE LOADI0

SUBROUTINE LOADI1 (ILUN, I1)
INTEGER                   :: ILUN
INTEGER (KIND=JPIM), POINTER :: I1 (:)
INTEGER :: IL (1), IB (1)
READ (ILUN) IL
READ (ILUN) IB
ALLOCATE (I1 (IL (1): IB (1)))
READ (ILUN) I1
END SUBROUTINE LOADI1

SUBROUTINE LOADI2 (ILUN, I2)
INTEGER                   :: ILUN
INTEGER (KIND=JPIM), POINTER :: I2 (:,:)
INTEGER :: IL (2), IB (2)
READ (ILUN) IL
READ (ILUN) IB
ALLOCATE (I2 (IL (1): IB (1), IL (2): IB (2)))
READ (ILUN) I2
END SUBROUTINE LOADI2

SUBROUTINE LOADI3 (ILUN, I3)
INTEGER                   :: ILUN
INTEGER (KIND=JPIM), POINTER :: I3 (:,:,:)
INTEGER :: IL (3), IB (3)
READ (ILUN) IL
READ (ILUN) IB
ALLOCATE (I3 (IL (1): IB (1), IL (2): IB (2), IL (3): IB (3)))
READ (ILUN) I3
END SUBROUTINE LOADI3

SUBROUTINE DIFFL0 (CDNAME, L0, L0_1)
CHARACTER (LEN=*) :: CDNAME
LOGICAL :: L0, L0_1
IF (.NOT. (L0 .EQV. L0_1)) THEN
  WRITE (*, '(A32,24X,3L25)') CDNAME, L0, L0_1, .FALSE.
ENDIF
END SUBROUTINE DIFFL0

SUBROUTINE LOADL0 (ILUN, L0)
INTEGER :: ILUN
LOGICAL :: L0
READ (ILUN) L0
END SUBROUTINE LOADL0

SUBROUTINE DIFFC0 (CDNAME, C0, C0_1)
CHARACTER (LEN=*) :: CDNAME
CHARACTER (LEN=*) :: C0, C0_1
IF (C0 .NE. C0_1) THEN
  WRITE (*, '(A32,24X,2A25)') CDNAME, C0, C0_1
ENDIF
END SUBROUTINE DIFFC0

SUBROUTINE LOADC0 (ILUN, C0)
INTEGER           :: ILUN
CHARACTER (LEN=*) :: C0
READ (ILUN) C0
END SUBROUTINE LOADC0

SUBROUTINE LOAD_TGSGEOM (ILUN, YDGSGEOM)

USE YOMGSGEOM, ONLY : TGSGEOM

INTEGER :: ILUN
TYPE (TGSGEOM) :: YDGSGEOM

CALL LOAD (ILUN, YDGSGEOM%GM    )
CALL LOAD (ILUN, YDGSGEOM%GMAPPA)
CALL LOAD (ILUN, YDGSGEOM%GNORDL)
CALL LOAD (ILUN, YDGSGEOM%GNORDM)
CALL LOAD (ILUN, YDGSGEOM%GOMVRL)
CALL LOAD (ILUN, YDGSGEOM%GOMVRM)
CALL LOAD (ILUN, YDGSGEOM%RCORI )
CALL LOAD (ILUN, YDGSGEOM%RCORIC)

END SUBROUTINE

SUBROUTINE LOAD_TOROG (ILUN, YDOROG)

USE YOMOROG  , ONLY : TOROG

INTEGER :: ILUN
TYPE (TOROG) :: YDOROG

CALL LOAD (ILUN, YDOROG%OROG)

END SUBROUTINE

SUBROUTINE LOAD_TGMV (ILUN, YDGMV)

USE YOMGMV

INTEGER :: ILUN
TYPE (TGMV) :: YDGMV

CALL LOAD (ILUN, YDGMV%NDIMGMV)
CALL LOAD (ILUN, YDGMV%NDIMGMVS)
CALL LOAD (ILUN, YDGMV%YT0%MDIV)
CALL LOAD (ILUN, YDGMV%YT0%MSP)
CALL LOAD (ILUN, YDGMV%YT0%MSPD)
CALL LOAD (ILUN, YDGMV%YT0%MSPL)
CALL LOAD (ILUN, YDGMV%YT0%MSPM)
CALL LOAD (ILUN, YDGMV%YT0%MSVD)
CALL LOAD (ILUN, YDGMV%YT0%MT)
CALL LOAD (ILUN, YDGMV%YT0%MTL)
CALL LOAD (ILUN, YDGMV%YT0%MTM)
CALL LOAD (ILUN, YDGMV%YT0%MU)
CALL LOAD (ILUN, YDGMV%YT0%MV)
CALL LOAD (ILUN, YDGMV%YT1%MNHX)
CALL LOAD (ILUN, YDGMV%YT1%MSP)
CALL LOAD (ILUN, YDGMV%YT1%MSPD)
CALL LOAD (ILUN, YDGMV%YT1%MSVD)
CALL LOAD (ILUN, YDGMV%YT1%MT)
CALL LOAD (ILUN, YDGMV%YT1%MU)
CALL LOAD (ILUN, YDGMV%YT1%MV)
CALL LOAD (ILUN, YDGMV%YT1%NDIM)
CALL LOAD (ILUN, YDGMV%YT1%NDIMS)
CALL LOAD (ILUN, YDGMV%YT9%MCSPDNL)
CALL LOAD (ILUN, YDGMV%YT9%MCSPNL)
CALL LOAD (ILUN, YDGMV%YT9%MCTNL)
CALL LOAD (ILUN, YDGMV%YT9%MCUNL)
CALL LOAD (ILUN, YDGMV%YT9%MCVNL)
CALL LOAD (ILUN, YDGMV%YT9%MCVWVNL)
CALL LOAD (ILUN, YDGMV%YT9%MDIV)
CALL LOAD (ILUN, YDGMV%YT9%MEDOT)
CALL LOAD (ILUN, YDGMV%YT9%MGW)
CALL LOAD (ILUN, YDGMV%YT9%MNHX)
CALL LOAD (ILUN, YDGMV%YT9%MRDLASR)
CALL LOAD (ILUN, YDGMV%YT9%MSP)
CALL LOAD (ILUN, YDGMV%YT9%MSPD)
CALL LOAD (ILUN, YDGMV%YT9%MSPDNL)
CALL LOAD (ILUN, YDGMV%YT9%MSPL)
CALL LOAD (ILUN, YDGMV%YT9%MSPM)
CALL LOAD (ILUN, YDGMV%YT9%MSPNL)
CALL LOAD (ILUN, YDGMV%YT9%MSPNL_SI)
CALL LOAD (ILUN, YDGMV%YT9%MSVD)
CALL LOAD (ILUN, YDGMV%YT9%MT)
CALL LOAD (ILUN, YDGMV%YT9%MTL)
CALL LOAD (ILUN, YDGMV%YT9%MTM)
CALL LOAD (ILUN, YDGMV%YT9%MTNL)
CALL LOAD (ILUN, YDGMV%YT9%MU)
CALL LOAD (ILUN, YDGMV%YT9%MUNL)
CALL LOAD (ILUN, YDGMV%YT9%MV)
CALL LOAD (ILUN, YDGMV%YT9%MVCASRS)
CALL LOAD (ILUN, YDGMV%YT9%MVNL)
CALL LOAD (ILUN, YDGMV%YT9%MVWVNL)

END SUBROUTINE

SUBROUTINE LOAD_TYPE_GFL_COMP1 (ILUN, YDCOMP)
USE YOM_YGFL
INTEGER :: ILUN
TYPE (TYPE_GFL_COMP), POINTER :: YDCOMP (:)
INTEGER :: ILB (1), IUB (1), J
READ (ILUN) ILB
READ (ILUN) IUB
ALLOCATE (YDCOMP (ILB (1):IUB (1)))
DO J = ILB (1), IUB (1)
CALL LOAD_TYPE_GFL_COMP0 (ILUN, YDCOMP (J))
ENDDO
END SUBROUTINE

SUBROUTINE LOAD_TYPE_GFL_COMP0 (ILUN, YDCOMP)
USE YOM_YGFL
INTEGER :: ILUN
TYPE (TYPE_GFL_COMP) :: YDCOMP 
CALL LOAD (ILUN, YDCOMP%CNAME     )
CALL LOAD (ILUN, YDCOMP%IGRBCODE  )
CALL LOAD (ILUN, YDCOMP%LADV      )
CALL LOAD (ILUN, YDCOMP%LADV5     )
CALL LOAD (ILUN, YDCOMP%LTDIABLIN )
CALL LOAD (ILUN, YDCOMP%LHORTURB  )
CALL LOAD (ILUN, YDCOMP%NREQIN    )
CALL LOAD (ILUN, YDCOMP%LREQOUT   )
CALL LOAD (ILUN, YDCOMP%LGPINGP   )
CALL LOAD (ILUN, YDCOMP%LGP       )
CALL LOAD (ILUN, YDCOMP%LSP       )
CALL LOAD (ILUN, YDCOMP%LCDERS    )
CALL LOAD (ILUN, YDCOMP%LACTIVE   )
CALL LOAD (ILUN, YDCOMP%LTHERMACT )
CALL LOAD (ILUN, YDCOMP%R         )
CALL LOAD (ILUN, YDCOMP%RCP       )
CALL LOAD (ILUN, YDCOMP%LT9       )
CALL LOAD (ILUN, YDCOMP%LT1       )
CALL LOAD (ILUN, YDCOMP%LT5       )
CALL LOAD (ILUN, YDCOMP%LPHY      )
CALL LOAD (ILUN, YDCOMP%LPT       )
CALL LOAD (ILUN, YDCOMP%LTRAJIO   )
CALL LOAD (ILUN, YDCOMP%LDIAG     )
CALL LOAD (ILUN, YDCOMP%LPC       )
CALL LOAD (ILUN, YDCOMP%REFVALI   )
CALL LOAD (ILUN, YDCOMP%LADJUST0  )
CALL LOAD (ILUN, YDCOMP%LADJUST1  )
CALL LOAD (ILUN, YDCOMP%NCOUPLING )
CALL LOAD (ILUN, YDCOMP%REFVALC   )
CALL LOAD (ILUN, YDCOMP%LBIPER    )
CALL LOAD (ILUN, YDCOMP%CSLINT    )
CALL LOAD (ILUN, YDCOMP%MP        )
CALL LOAD (ILUN, YDCOMP%MPL       )
CALL LOAD (ILUN, YDCOMP%MPM       )
CALL LOAD (ILUN, YDCOMP%MP9       )
CALL LOAD (ILUN, YDCOMP%MP9_PH    )
CALL LOAD (ILUN, YDCOMP%MP1       )
CALL LOAD (ILUN, YDCOMP%MP5       )
CALL LOAD (ILUN, YDCOMP%MP5L      )
CALL LOAD (ILUN, YDCOMP%MP5M      )
CALL LOAD (ILUN, YDCOMP%MPSLP     )
CALL LOAD (ILUN, YDCOMP%MPSP      )
CALL LOAD (ILUN, YDCOMP%MP_SPL    )
CALL LOAD (ILUN, YDCOMP%MP_SL1    )
CALL LOAD (ILUN, YDCOMP%MP_SLX    )
CALL LOAD (ILUN, YDCOMP%MPPT      )
CALL LOAD (ILUN, YDCOMP%MPPC      )
CALL LOAD (ILUN, YDCOMP%LWATER    )
CALL LOAD (ILUN, YDCOMP%LPRECIP   )
CALL LOAD (ILUN, YDCOMP%RLZER     )
CALL LOAD (ILUN, YDCOMP%NCOUPLO4  )
CALL LOAD (ILUN, YDCOMP%LASSIM    )
CALL LOAD (ILUN, YDCOMP%IGRIBDV   )
CALL LOAD (ILUN, YDCOMP%IGRIBTC   )
CALL LOAD (ILUN, YDCOMP%IGRIBSFC  )
CALL LOAD (ILUN, YDCOMP%LDIFF     )
CALL LOAD (ILUN, YDCOMP%LCONV     )
CALL LOAD (ILUN, YDCOMP%RMOLMASS  )
CALL LOAD (ILUN, YDCOMP%REFOLD    )
CALL LOAD (ILUN, YDCOMP%HENRYA    )
CALL LOAD (ILUN, YDCOMP%HENRYB    )
CALL LOAD (ILUN, YDCOMP%LNEGFIX   )
CALL LOAD (ILUN, YDCOMP%LCOMAD    )
CALL LOAD (ILUN, YDCOMP%LMASSFIX  )
CALL LOAD (ILUN, YDCOMP%BETAMFBC  )
END SUBROUTINE
END MODULE LOAD_MOD

