INTERFACE
SUBROUTINE SIGAM(KLEV,KLON,PD,PT,PSP,KNLON,KFLEVG)
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMCT0   , ONLY : LNHDYN
USE YOMCST   , ONLY : RD
USE YOMDYN   , ONLY : YRDYN
USE YOMVERT  , ONLY : YRVETA, YRVFE
USE YOMCVER  , ONLY : LVERTFE, LRNHC1, LVFE_INTB
IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV
INTEGER(KIND=JPIM),INTENT(IN)    :: KLON
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PD(1+(KFLEVG-1)*KLEV+(KNLON-1)*KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PT(1+(KFLEVG-1)*KLEV+(KNLON-1)*KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSP(KNLON)
INTEGER(KIND=JPIM),INTENT(IN)    :: KNLON
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLEVG
END SUBROUTINE SIGAM
END INTERFACE
