INTERFACE
SUBROUTINE SITNU(YRVFE, YRVETA, YRDYN, YRDIMV, KIDIA,KFDIA,KLON,KFLEVG,PD,PT,PSP,KSTPT,KSTSZ,PSTACK)

USE PARKIND1 , ONLY : JPIM, JPRB

USE YOMCT0   , ONLY : LNHDYN
USE YOMDIMV  , ONLY : TDIMV
USE YOMCST   , ONLY : RKAPPA
USE YOMDYN   , ONLY : TDYN
USE YOMVERT  , ONLY : TVETA, TVFE
USE YOMCVER  , ONLY : LVERTFE, LRNHC1, LVFE_INTB

TYPE (TDIMV),      INTENT(IN) :: YRDIMV
TYPE (TDYN),       INTENT(IN) :: YRDYN
TYPE (TVETA),      INTENT(IN) :: YRVETA
TYPE (TVFE),       INTENT(IN) :: YRVFE
INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN)    :: KLON
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLEVG
REAL(KIND=JPRB)   ,INTENT(IN)    :: PD(KLON,KFLEVG)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PT(KLON,KFLEVG)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSP(KLON) 

INTEGER(KIND=JPIM),INTENT(IN)    :: KSTSZ
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTPT
REAL (KIND=JPRB)   ,INTENT(INOUT) :: PSTACK (KSTSZ)

END SUBROUTINE SITNU

END INTERFACE
