INTERFACE
SUBROUTINE SITNU(KLEV,KLON,PD,PT,PSP,KNLON)
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMCT0   , ONLY : LNHDYN
USE YOMDIMV  , ONLY : YRDIMV
USE YOMCST   , ONLY : RKAPPA
USE YOMDYN   , ONLY : YRDYN
USE YOMVERT  , ONLY : YRVETA, YRVFE
USE YOMCVER  , ONLY : LVERTFE, LRNHC1, LVFE_INTB
IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV
INTEGER(KIND=JPIM),INTENT(IN)    :: KLON
REAL(KIND=JPRB)   ,INTENT(IN)    :: PD(1+(YRDIMV%NFLEVG-1)*KLEV+(KNLON-1)*KLON)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PT(1+(YRDIMV%NFLEVG-1)*KLEV+(KNLON-1)*KLON)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSP(KNLON)
INTEGER(KIND=JPIM),INTENT(IN)    :: KNLON
END SUBROUTINE SITNU
END INTERFACE
