MODULE PTRSLB1

IMPLICIT NONE

INTEGER, PARAMETER :: JPRB = 8, JPIM = 4

TYPE :: TPTRSLB1
INTEGER(KIND=JPIM) :: NFLDSLB1

INTEGER(KIND=JPIM) :: MSLBUF1
INTEGER(KIND=JPIM) :: MSLB1U9
INTEGER(KIND=JPIM) :: MSLB1V9
INTEGER(KIND=JPIM) :: MSLB1T9
INTEGER(KIND=JPIM) :: MSLB1GFL9
INTEGER(KIND=JPIM) :: MSLB1GFLSP9
INTEGER(KIND=JPIM) :: MSLB1PD9
INTEGER(KIND=JPIM) :: MSLB1VD9
INTEGER(KIND=JPIM) :: MSLB1NHX9
INTEGER(KIND=JPIM) :: MSLB1UR0
INTEGER(KIND=JPIM) :: MSLB1VR0
INTEGER(KIND=JPIM) :: MSLB1WR0
INTEGER(KIND=JPIM) :: MSLB1WRA
INTEGER(KIND=JPIM) :: MSLB1UR9
INTEGER(KIND=JPIM) :: MSLB1VR9
INTEGER(KIND=JPIM) :: MSLB1DBBC9
INTEGER(KIND=JPIM) :: MSLB1DPHI9
INTEGER(KIND=JPIM) :: MSLB1GWS9
INTEGER(KIND=JPIM) :: MSLB1U0
INTEGER(KIND=JPIM) :: MSLB1V0
INTEGER(KIND=JPIM) :: MSLB1T0
INTEGER(KIND=JPIM) :: MSLB1PD0
INTEGER(KIND=JPIM) :: MSLB1VD0
INTEGER(KIND=JPIM) :: MSLB1C9
INTEGER(KIND=JPIM) :: MSLB1SP9
INTEGER(KIND=JPIM) :: MSLB1SP0
INTEGER(KIND=JPIM) :: MSLB1C0
INTEGER(KIND=JPIM) :: MSLB1UP9
INTEGER(KIND=JPIM) :: MSLB1VP9
INTEGER(KIND=JPIM) :: MSLB1TP9
INTEGER(KIND=JPIM) :: MSLB1GFLP9
INTEGER(KIND=JPIM) :: MSLB1RSSA9
INTEGER(KIND=JPIM) :: MSLB1U9_SI
INTEGER(KIND=JPIM) :: MSLB1V9_SI
INTEGER(KIND=JPIM) :: MSLB1T9_SI
INTEGER(KIND=JPIM) :: MSLB1PD9_SI
INTEGER(KIND=JPIM) :: MSLB1VD9_SI
INTEGER(KIND=JPIM) :: MSLB1C9_SI
INTEGER(KIND=JPIM) :: MSLB1UF9
INTEGER(KIND=JPIM) :: MSLB1VF9
INTEGER(KIND=JPIM) :: MSLB1TF9
INTEGER(KIND=JPIM) :: MSLB1GFLF9
INTEGER(KIND=JPIM) :: MSLB1VDF9
INTEGER(KIND=JPIM) :: MSLB1GFLSPF9
END TYPE TPTRSLB1

TYPE(TPTRSLB1) :: YRPTRSLB1 
!$acc declare create(YRPTRSLB1)


END MODULE PTRSLB1

USE PTRSLB1  , ONLY : YRPTRSLB1

IMPLICIT NONE

INTEGER :: IBL, ICOUNT, KLON, JJ, JIDIA, JFDIA, KIDIA, KFDIA


YRPTRSLB1%NFLDSLB1 = 2713

PRINT *, __FILE__//':', __LINE__
PRINT *, YRPTRSLB1%NFLDSLB1

!$acc kernels
PRINT *, YRPTRSLB1%NFLDSLB1
!$acc end kernels
PRINT *, __FILE__//':', __LINE__


KLON = 64
KIDIA = 1
KFDIA = KLON

ICOUNT = 1

PRINT *, __FILE__//':', __LINE__
PRINT *, YRPTRSLB1%NFLDSLB1
!$acc kernels
PRINT *, YRPTRSLB1%NFLDSLB1
!$acc end kernels
PRINT *, __FILE__//':', __LINE__

!$acc update device (YRPTRSLB1)

#ifdef ACC
!$acc parallel loop gang vector private(IBL) private(JJ) collapse(2) 
#else
!$OMP PARALLEL DO PRIVATE (IBL,JJ,JIDIA,JFDIA)
#endif

DO IBL = 1, ICOUNT
  DO JJ = KIDIA, KFDIA
  PRINT *, YRPTRSLB1%NFLDSLB1
    JIDIA=JJ
    JFDIA=JJ
  ENDDO

ENDDO
#ifdef ACC
!$acc end parallel
#else
!$OMP END PARALLEL DO
#endif


END 
