#include "simple4.h"
#define ATTR_ARG

USE PARKIND1,  ONLY : JPIM, JPRB
USE YOMGMV,    ONLY : TGMV
USE YOMOROG,   ONLY : TOROG
USE YOMGSGEOM, ONLY : TGSGEOM
USE YOMDIMV  , ONLY : YRDIMV
USE LOAD_MOD

USE XRD_GETOPTIONS
USE YOM_YGFL

IMPLICIT NONE

INTERFACE SETALL
  PROCEDURE SETALLI1
  PROCEDURE SETALLI2
  PROCEDURE SETALLX1
  PROCEDURE SETALLX2
  PROCEDURE SETALLX3
  PROCEDURE SETALL_GMV
  PROCEDURE SETALL_TGSGEOM
  PROCEDURE SETALL_TOROG
END INTERFACE

INTERFACE DDIFF
  PROCEDURE DDIFFX1
  PROCEDURE DDIFFX2
  PROCEDURE DDIFFX3
END INTERFACE

INTEGER(KIND=JPIM), ALLOCATABLE  :: IFDIA (:)

TYPE(TGMV)        , POINTER      :: YDGMV_ALL(:)
INTEGER(KIND=JPIM)               :: KIDIA 
INTEGER(KIND=JPIM)               :: KFDIA 
INTEGER(KIND=JPIM), POINTER      :: KSETTLOFF_ALL(:,:)
REAL(KIND=JPRB)                  :: PBETADT 
REAL(KIND=JPRB)                  :: PDT 
REAL(KIND=JPRB)   , POINTER      :: PSLHDA_ALL(:,:)
REAL(KIND=JPRB)   , POINTER      :: PSLHDD0_ALL(:,:)
TYPE(TGSGEOM)     , POINTER      :: YDGSGEOM_ALL(:) 
TYPE(TOROG)       , POINTER      :: YDOROG_ALL(:)
REAL(KIND=JPRB)   , POINTER      :: POROGL_ALL(:,:)
REAL(KIND=JPRB)   , POINTER      :: POROGM_ALL(:,:) 
REAL(KIND=JPRB)   , POINTER      :: PVCRSSA9F_ALL(:,:,:) 
REAL(KIND=JPRB)   , POINTER      :: PNHXT9_ALL(:,:,:) 
REAL(KIND=JPRB)   , POINTER      :: PVCRS0_ALL(:,:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PVCW0F_ALL(:,:,:) 
REAL(KIND=JPRB)   , POINTER      :: PWDLW0F_ALL(:,:,:) 
REAL(KIND=JPRB)   , POINTER      :: PRDLR0_ALL(:,:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PRDLR9_ALL(:,:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PNHXT0_ALL(:,:,:) 
REAL(KIND=JPRB)   , POINTER      :: PRES0_ALL(:,:,:) 
REAL(KIND=JPRB)   , POINTER      :: PRDELP0_ALL(:,:,:) 
REAL(KIND=JPRB)   , POINTER      :: PCTY0_ALL(:,:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PUVH0_ALL(:,:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PATND_ALL(:,:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PDBBC_ALL(:,:)
REAL(KIND=JPRB)   , POINTER      :: PRDPHI_ALL(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PGWT0_ALL(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PGWT9_ALL(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PGFL_ALL(:,:,:,:) 
REAL(KIND=JPRB)   , POINTER      :: PGMV_ALL(:,:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PGMVS_ALL(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PB1_ALL(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PB2_ALL(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PGMVT1_ALL(:,:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PGMVT1S_ALL(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PGWS_ALL(:,:)
REAL(KIND=JPRB)   , POINTER      :: PGMVTNDSI_ALL(:,:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PWRL95_ALL(:,:,:)
REAL(KIND=JPRB)   , POINTER      :: PSTACK_ALL(:,:,:)


INTEGER :: IBL, ICOUNT, KLON, JJ, JIDIA, JFDIA
INTEGER :: KPSTSZ, KPSTPT
INTEGER :: ICOUNT1, KLON1
INTEGER :: ICOUNT0, KLON0
LOGICAL :: LLDIFF
CHARACTER (LEN=32) :: CLCASE
INTEGER, POINTER :: IDIFFBLOCK (:) => NULL ()

#include "lacdyn.intfb.h"

YDGSGEOM_ALL => NULL ()

CALL INITOPTIONS ()
CALL GETOPTION ("--case", CLCASE, MND = .TRUE.)
CALL GETOPTION ("--diff", LLDIFF)
CALL GETOPTION ("--diff-block-list", IDIFFBLOCK)
ICOUNT1 = 0 
CALL GETOPTION ("--count", ICOUNT1)
KLON1 = 0 
!CALL CHECKOPTIONS ()



OPEN (77, FORM='FORMATTED', FILE=TRIM (CLCASE)//'/LACDYN.COUNT')
READ (77, *) ICOUNT
CLOSE (77)

IF (ICOUNT1 == 0) ICOUNT1 = ICOUNT

ALLOCATE (IFDIA (ICOUNT))

CALL LACDYN_LOAD_ALL (TRIM (CLCASE)//"/LACDYN.CONST")

CALL OPEN_LOAD (TRIM (CLCASE)//"/LACDYN")

PRINT *, "-- READ"

DO IBL = 1, ICOUNT


#define SET(x) CALL SETALL (x##_ALL)

  SET (YDGMV)
  CALL LOAD (ILUN_IN, KIDIA)
  CALL LOAD (ILUN_IN, IFDIA (IBL))
  IF (IBL == 1) KLON = IFDIA (IBL)
  IF (KLON1 == 0) KLON1 = KLON
  CALL LOAD (ILUN_IN, PBETADT)
  CALL LOAD (ILUN_IN, PDT)
  SET (YDGSGEOM)
  SET (YDOROG)
  SET (PSLHDA)
  SET (PSLHDD0)
  CALL SETALL (KSETTLOFF_ALL, .FALSE.)
  SET (POROGL)
  SET (POROGM)
  CALL SETALL (PVCRSSA9F_ALL, .FALSE.)
  SET (PNHXT9)
  CALL SETALL (PVCRS0_ALL, .FALSE.)
  CALL SETALL (PVCW0F_ALL, .FALSE.)
  CALL SETALL (PWDLW0F_ALL, .FALSE.)
  CALL SETALL (PRDLR0_ALL, .FALSE.)
  CALL SETALL (PRDLR9_ALL, .FALSE.)
  SET (PNHXT0)
  SET (PRES0)
  SET (PRDELP0)
  SET (PCTY0)
  SET (PUVH0)
  SET (PATND)
  CALL SETALL (PDBBC_ALL, .FALSE.)
  CALL SETALL (PRDPHI_ALL, .FALSE.)
  CALL SETALL (PGWT0_ALL, .FALSE.)
  CALL SETALL (PGWT9_ALL, .FALSE.)
  SET (PGFL)
  SET (PGMV)
  SET (PGMVS)
  SET (PB1)
  SET (PB2)
  SET (PGMVT1)
  SET (PGMVT1S)
  CALL SETALL (PGWS_ALL, .FALSE.)
! SET (PGMVTNDSI)
  SET (PWRL95)

#undef SET

ENDDO


KLON0 = KLON; ICOUNT0 = ICOUNT
KLON = KLON1; ICOUNT = ICOUNT1

KIDIA = 1
KFDIA = KLON

ALLOCATE (PGMVTNDSI_ALL (1, 1, 1, 1))

KPSTSZ = 15 * YRDIMV%NFLEVG
KPSTPT = 1

ALLOCATE (PSTACK_ALL (KLON, KPSTSZ, ICOUNT))
#ifdef PRINTBEFORE 
DO IBL = 1, ICOUNT

#define DIFF(x) CALL DDIFF (#x, x##_ALL, LLDIFF)
  DIFF (PGMV)
  DIFF (PGMVS)
  DIFF (PB1)
  DIFF (PB2)
  DIFF (PGMVT1)
  DIFF (PGMVT1S)
  DIFF (PGWS)
! DIFF (PGMVTNDSI)
  CALL DDIFF ("PWRL95", PWRL95_ALL, .FALSE.)

#undef DIFF

ENDDO
#endif 


PRINT *, "-- RUN",KIDIA,KFDIA
#ifdef ACC
!$acc parallel loop gang vector private(IBL) private(JJ) collapse(2)
#else
!$OMP PARALLEL DO PRIVATE (IBL,JJ,JIDIA,JFDIA)
#endif
DO IBL = 1, ICOUNT
  DO JJ = KIDIA, KFDIA
    JIDIA=JJ
    JFDIA=JJ
    CALL LACDYN(PSTACK_ALL(:,:,IBL),KPSTSZ,KPSTPT,KLON,YDGMV_ALL(IBL),JIDIA,JFDIA,PBETADT,PDT,&
     & PSLHDA_ALL(:,IBL),PSLHDD0_ALL(:,IBL),YDGSGEOM_ALL(IBL),YDOROG_ALL(IBL),POROGL_ALL(:,IBL),&
     & POROGM_ALL(:,IBL),PVCRSSA9F_ALL(:,:,IBL),PNHXT9_ALL(:,:,IBL),&
     & PVCRS0_ALL(:,:,:,IBL),PVCW0F_ALL(:,:,IBL),PWDLW0F_ALL(:,:,IBL),&
     & PRDLR0_ALL(:,:,:,IBL),PRDLR9_ALL(:,:,:,IBL),PNHXT0_ALL(:,:,IBL),&
     & PRES0_ALL(:,:,IBL),PRDELP0_ALL(:,:,IBL),PCTY0_ALL(:,:,:,IBL),PUVH0_ALL(:,:,:,IBL),&
     & PATND_ALL(:,:,:,IBL),PDBBC_ALL(:,IBL),PRDPHI_ALL(:,:,IBL),PGWT0_ALL(:,:,IBL),&
     & PGWT9_ALL(:,:,IBL),PGFL_ALL(:,:,:,IBL),&
     & KSETTLOFF_ALL(:,IBL),PGMV_ALL(:,:,:,IBL),PGMVS_ALL(:,:,IBL),PB1_ALL(:,:,IBL),&
     & PB2_ALL(:,:,IBL),PGMVT1_ALL(:,:,:,IBL),PGMVT1S_ALL(:,:,IBL),PGWS_ALL(:,IBL),&
     & PGMVTNDSI_ALL(:,:,:,IBL),PWRL95_ALL(:,:,IBL))

  ENDDO

ENDDO
#ifdef ACC
!$acc end parallel
#else
!$OMP END PARALLEL DO
#endif



IF (LLDIFF .AND. ICOUNT0 == ICOUNT1 .AND. KLON1 == KLON0) THEN

PRINT *, "-- DIFF"

DO IBL = 1, ICOUNT

#define DIFF(x) CALL DDIFF (#x, x##_ALL, LLDIFF)
  DIFF (PGMV)
  DIFF (PGMVS)
  DIFF (PB1)
  DIFF (PB2)
  DIFF (PGMVT1)
  DIFF (PGMVT1S)
  DIFF (PGWS)
! DIFF (PGMVTNDSI)
  CALL DDIFF ("PWRL95", PWRL95_ALL, .FALSE.)

#undef DIFF

ENDDO

ENDIF

CALL CLOSE_LOAD

CONTAINS

#include "contains.h"

SUBROUTINE SETALL_GMV (YDGMV_ALL)

TYPE (TGMV), POINTER :: YDGMV_ALL (:)
TYPE (TGMV) :: YLGMV
INTEGER (KIND=JPIM) :: IBL1

IF (IBL == 1) THEN
  ALLOCATE (YDGMV_ALL (ICOUNT1))
ENDIF

IF (IBL <= ICOUNT1) THEN
  CALL LOAD_TGMV (ILUN_IN, YDGMV_ALL (IBL))
ELSE
  CALL LOAD_TGMV (ILUN_IN, YLGMV)
ENDIF

IF (IBL == ICOUNT) THEN
  DO IBL1 = ICOUNT+1, ICOUNT1
    YDGMV_ALL (IBL1) = YDGMV_ALL (1)
  ENDDO
ENDIF

END SUBROUTINE

SUBROUTINE SETALL_TGSGEOM (YDGSGEOM_ALL)

TYPE (TGSGEOM), POINTER :: YDGSGEOM_ALL (:)
TYPE (TGSGEOM) :: YLGSGEOM
INTEGER :: IBL1

IF (IBL == 1) THEN
  ALLOCATE (YDGSGEOM_ALL (ICOUNT1))
ENDIF

IF (IBL <= ICOUNT1) THEN
  CALL LOAD_TGSGEOM (ILUN_IN, YDGSGEOM_ALL (IBL))
ELSE
  CALL LOAD_TGSGEOM (ILUN_IN, YLGSGEOM)
  DEALLOCATE (YLGSGEOM% RCORI  )
  DEALLOCATE (YLGSGEOM% RCORIC )
  DEALLOCATE (YLGSGEOM% GM     )
  DEALLOCATE (YLGSGEOM% GMAPPA )
  DEALLOCATE (YLGSGEOM% GOMVRL )
  DEALLOCATE (YLGSGEOM% GOMVRM )
  DEALLOCATE (YLGSGEOM% GNORDL )
  DEALLOCATE (YLGSGEOM% GNORDM )
ENDIF


IF (IBL == ICOUNT) THEN

  DO IBL1 = ICOUNT+1, ICOUNT1
    ALLOCATE (YDGSGEOM_ALL (IBL1)% RCORI   (KLON))
    ALLOCATE (YDGSGEOM_ALL (IBL1)% RCORIC  (KLON))
    ALLOCATE (YDGSGEOM_ALL (IBL1)% GM      (KLON))
    ALLOCATE (YDGSGEOM_ALL (IBL1)% GMAPPA  (KLON))
    ALLOCATE (YDGSGEOM_ALL (IBL1)% GOMVRL  (KLON))
    ALLOCATE (YDGSGEOM_ALL (IBL1)% GOMVRM  (KLON))
    ALLOCATE (YDGSGEOM_ALL (IBL1)% GNORDL  (KLON))
    ALLOCATE (YDGSGEOM_ALL (IBL1)% GNORDM  (KLON))
  
    YDGSGEOM_ALL (IBL1)% RCORI    = YDGSGEOM_ALL (1)% RCORI  
    YDGSGEOM_ALL (IBL1)% RCORIC   = YDGSGEOM_ALL (1)% RCORIC 
    YDGSGEOM_ALL (IBL1)% GM       = YDGSGEOM_ALL (1)% GM     
    YDGSGEOM_ALL (IBL1)% GMAPPA   = YDGSGEOM_ALL (1)% GMAPPA 
    YDGSGEOM_ALL (IBL1)% GOMVRL   = YDGSGEOM_ALL (1)% GOMVRL 
    YDGSGEOM_ALL (IBL1)% GOMVRM   = YDGSGEOM_ALL (1)% GOMVRM 
    YDGSGEOM_ALL (IBL1)% GNORDL   = YDGSGEOM_ALL (1)% GNORDL 
    YDGSGEOM_ALL (IBL1)% GNORDM   = YDGSGEOM_ALL (1)% GNORDM 
  
  ENDDO

ENDIF

END SUBROUTINE

SUBROUTINE SETALL_TOROG (YDOROG_ALL)

TYPE (TOROG), POINTER :: YDOROG_ALL (:)
TYPE (TOROG) :: YLOROG
INTEGER :: IBL1

IF (IBL == 1) THEN
  ALLOCATE (YDOROG_ALL (ICOUNT1))
ENDIF

IF (IBL <= ICOUNT1) THEN
  CALL LOAD_TOROG (ILUN_IN, YDOROG_ALL (IBL))
ELSE
  CALL LOAD_TOROG (ILUN_IN, YLOROG)
  DEALLOCATE (YLOROG%OROG)
ENDIF

IF (IBL == ICOUNT) THEN

  DO IBL1 = ICOUNT+1, ICOUNT1
    ALLOCATE (YDOROG_ALL (IBL1)% OROG   (KLON))
  
    YDOROG_ALL (IBL1)% OROG    = YDOROG_ALL (1)% OROG  
  
  ENDDO

ENDIF

END SUBROUTINE

END 
