MODULE YOEPHY

USE PARKIND1, ONLY : JPRB, JPIM

IMPLICIT NONE


!     -----------------------------------------------------------------
!*    ** *YOEPHY* - SWITCHES RELATED TO DIABATIC PROCESSES
!     -----------------------------------------------------------------

!        * E.C.M.W.F. PHYSICS PACKAGE *

TYPE :: TEPHY
LOGICAL :: LEPHYS
LOGICAL :: LECOND
LOGICAL :: LECUMF
LOGICAL :: LEDCLD
LOGICAL :: LEEVAP
LOGICAL :: LEGWDG
LOGICAL :: LEGWWMS
LOGICAL :: LEOZOC
LOGICAL :: LEQNGT
LOGICAL :: LERADI
LOGICAL :: LERADS
LOGICAL :: LESICE
LOGICAL :: LESURF
LOGICAL :: LEVDIF
LOGICAL :: LAGPHY
LOGICAL :: LEPCLD
LOGICAL :: LEO3CH
LOGICAL :: LO3CH_OLDVER
LOGICAL :: LO3CH_BMS
LOGICAL :: LECO2DIU
LOGICAL :: LNEEONLINE
LOGICAL :: LBUD23
LOGICAL :: LBUDCYCLE
LOGICAL :: LEMETHOX
LOGICAL :: LECURR
LOGICAL :: LVDFTRAC
LOGICAL :: LMFTRAC
LOGICAL :: LMFSCAV
LOGICAL :: LERAIN
LOGICAL :: LE4ALB
LOGICAL :: LEMWAVE
LOGICAL :: LEGBRAD
LOGICAL :: LERAINGG
LOGICAL :: LESMOS
LOGICAL :: LEOCWA
LOGICAL :: LEOCCO
LOGICAL :: LEOCSA
LOGICAL :: LEOCLA
LOGICAL :: LEVGEN
LOGICAL :: LESSRO
LOGICAL :: LEFLAKE
LOGICAL :: LEOCML
LOGICAL :: LEOBC
LOGICAL :: LEOBCICE
LOGICAL :: LEOCLAKE
LOGICAL :: LEOLAKESST
LOGICAL :: LOCMLTKE
LOGICAL :: LESMOSS
LOGICAL :: LECLIPQT0
LOGICAL :: LECLIPCLDT0
LOGICAL :: LDUCTDIA
LOGICAL :: LESN09
LOGICAL :: LELAIV
LOGICAL :: LECTESSEL
LOGICAL :: LEAGS
LOGICAL :: LSPCRM
REAL(KIND=JPRB) :: RTHRFRTI
REAL(KIND=JPRB) :: RLAIINT
INTEGER (KIND=JPIM) :: NPRACCL
LOGICAL :: LECLIM10D ! 10-day clim interpolation

!VARIABLES FOR THE FLUX ADJUSTMENT OF GPP/RECO
LOGICAL             :: LBFASCO2

! SOME VARIABLES RELATED TO THE DIFFERENT NBF CO2 CLIMATOLOGIES

! NCO2CLIMYY1    ===> First year in the NBF CO2 climatology
! NCO2CLIMYY2    ===> Last year in the NBF CO2 climatology
! NCO2CLIMN1     ===> starting time for the diurnally variable fluxes (in minutes)
! NCO2CLIMN2     ===> end time for the diurnally variable fluxes (in minutes)
! NCO2CLIMFRQ    ===> time frequency at which the diurnal cycle is provided (in minutes)

INTEGER(KIND=JPIM) :: NCO2CLIMYY1
INTEGER(KIND=JPIM) :: NCO2CLIMYY2
INTEGER(KIND=JPIM) :: NCO2CLIMN1
INTEGER(KIND=JPIM) :: NCO2CLIMN2
INTEGER(KIND=JPIM) :: NCO2CLIMFRQ

!     REFERENCE.
!     ----------

!     F Vitart      E.C.M.W.F.      06/08/10

! RNORTHML : northern limit domain
! RSOUTHML : southern limit
! RWESTML : western limit
! REASTML : eastern limit
! INVML:  =true: ML is applied inside the domain, =false: ML is applied outside the domain

REAL(KIND=JPRB) :: RNORTHML
REAL(KIND=JPRB) :: RSOUTHML
REAL(KIND=JPRB) :: RWESTML
REAL(KIND=JPRB) :: REASTML

LOGICAL :: INVML
LOGICAL :: LFPOS_EC_PHYS

! YSURF :  Pointer to surface package configuration

END TYPE TEPHY

TYPE(TEPHY) :: YREPHY 
!$acc declare create(YREPHY)
END MODULE
