MODULE YOEPHY

USE PARKIND1, ONLY : JPRB, JPIM

IMPLICIT NONE

SAVE

!     -----------------------------------------------------------------
!*    ** *YOEPHY* - SWITCHES RELATED TO DIABATIC PROCESSES
!     -----------------------------------------------------------------

!        * E.C.M.W.F. PHYSICS PACKAGE *

TYPE :: TEPHY
LOGICAL :: LEPHYS
LOGICAL :: LECOND
LOGICAL :: LECUMF
LOGICAL :: LEDCLD
LOGICAL :: LEEVAP
LOGICAL :: LEGWDG
LOGICAL :: LEGWWMS
LOGICAL :: LEOZOC
LOGICAL :: LEQNGT
LOGICAL :: LERADI
LOGICAL :: LERADS
LOGICAL :: LESICE
LOGICAL :: LESURF
LOGICAL :: LEVDIF
LOGICAL :: LAGPHY
LOGICAL :: LEPCLD
LOGICAL :: LEO3CH
LOGICAL :: LO3CH_OLDVER
LOGICAL :: LO3CH_BMS
LOGICAL :: LECO2DIU
LOGICAL :: LNEEONLINE
LOGICAL :: LBUD23
LOGICAL :: LBUDCYCLE
LOGICAL :: LEMETHOX
LOGICAL :: LECURR
LOGICAL :: LVDFTRAC
LOGICAL :: LMFTRAC
LOGICAL :: LMFSCAV
LOGICAL :: LERAIN
LOGICAL :: LE4ALB
LOGICAL :: LEMWAVE
LOGICAL :: LEGBRAD
LOGICAL :: LERAINGG
LOGICAL :: LESMOS
LOGICAL :: LEOCWA
LOGICAL :: LEOCCO
LOGICAL :: LEOCSA
LOGICAL :: LEOCLA
LOGICAL :: LEVGEN
LOGICAL :: LESSRO
LOGICAL :: LEFLAKE
LOGICAL :: LEOCML
LOGICAL :: LEOBC
LOGICAL :: LEOBCICE
LOGICAL :: LEOCLAKE
LOGICAL :: LEOLAKESST
LOGICAL :: LOCMLTKE
LOGICAL :: LESMOSS
LOGICAL :: LECLIPQT0
LOGICAL :: LECLIPCLDT0
LOGICAL :: LDUCTDIA
LOGICAL :: LESN09
LOGICAL :: LELAIV
LOGICAL :: LECTESSEL
LOGICAL :: LEAGS
LOGICAL :: LSPCRM
REAL(KIND=JPRB) :: RTHRFRTI
REAL(KIND=JPRB) :: RLAIINT
INTEGER (KIND=JPIM) :: NPRACCL
LOGICAL :: LECLIM10D ! 10-day clim interpolation

!VARIABLES FOR THE FLUX ADJUSTMENT OF GPP/RECO
LOGICAL             :: LBFASCO2

! SOME VARIABLES RELATED TO THE DIFFERENT NBF CO2 CLIMATOLOGIES

! NCO2CLIMYY1    ===> First year in the NBF CO2 climatology
! NCO2CLIMYY2    ===> Last year in the NBF CO2 climatology
! NCO2CLIMN1     ===> starting time for the diurnally variable fluxes (in minutes)
! NCO2CLIMN2     ===> end time for the diurnally variable fluxes (in minutes)
! NCO2CLIMFRQ    ===> time frequency at which the diurnal cycle is provided (in minutes)

INTEGER(KIND=JPIM) :: NCO2CLIMYY1
INTEGER(KIND=JPIM) :: NCO2CLIMYY2
INTEGER(KIND=JPIM) :: NCO2CLIMN1
INTEGER(KIND=JPIM) :: NCO2CLIMN2
INTEGER(KIND=JPIM) :: NCO2CLIMFRQ

!     REFERENCE.
!     ----------

!     F Vitart      E.C.M.W.F.      06/08/10

! RNORTHML : northern limit domain
! RSOUTHML : southern limit
! RWESTML : western limit
! REASTML : eastern limit
! INVML:  =true: ML is applied inside the domain, =false: ML is applied outside the domain

REAL(KIND=JPRB) :: RNORTHML
REAL(KIND=JPRB) :: RSOUTHML
REAL(KIND=JPRB) :: RWESTML
REAL(KIND=JPRB) :: REASTML

LOGICAL :: INVML
LOGICAL :: LFPOS_EC_PHYS

! YSURF :  Pointer to surface package configuration

END TYPE TEPHY

TYPE(TEPHY), POINTER :: YREPHY => NULL()

!     REFERENCE.
!     ----------

!     J.-J. MORCRETTE       E.C.M.W.F.      91/07/14

!     MODIFICATIONS
!     -------------

!     P. Viterbo   ECMWF   03-12-2004  Include user-defined RTHRFRTI
!     G. Balsamo   ECMWF   14-03-2007  Include LEVGEN, LESSRO switches
!     G. Balsamo   ECMWF   07-04-2008  Include LEFLAKE switch
!     G. Balsamo   ECMWF   13-10-2008  Include LEOCML switch
!     F. Vitart    ECMWF   21-01-2013  Include LEOBC switch
!     G. Balsamo   ECMWF   13-10-2008  Include LESNWD switch
!     P. Lopez     ECMWF   24-01-2009  Include LDUCTDIA switch
!     G. Balsamo   ECMWF   24-02-2009  Include full set of SNOW switches
!     Y. Takaya    ECMWF   21-08-2009  Include LEOCLA switch
!     S. Boussetta/G.Balsamo May 2009  Include variable LAI switch LELAIV 
!     E. Dutra             18-11-2009  snow 2009 cleaning of logicals - LESN09 to activate all 
!     Y. Takaya/P. de Rosnay May 2020  SSS for SMOS
!     P. Lopez     ECMWF   14-08-2009  Include LEGBRAD switch and NPRACCL
!     S.Boussetta/G.Balsamo  Nov 2010  Include land carbon switch LECTESSEL
!     G.Balsamo    ECMWF   21-06-2011  Include LEAGS switch (CO2&Evap modularity)
!     P. Lopez     ECMWF   22-08-2012  Include LERAINGG switch for rain gauge assim.
!     S.Boussetta  Nov 2013  Include 10-day clim interpolation switch LECLIM10D
!     F. Vana & M. Kharoutdinov 06-Feb-2015  Super-parametrization scheme.
!     A. Agusti-Panareda   09-08-2013  Add flag for GPP/REC flux adjustment (LBFASCO2)
!     ------------------------------------------------------------------

!  NAME     TYPE     PURPOSE
!  ----  :  ----   : ---------------------------------------------------
! LEPHYS : LOGICAL : SWITCH THE FULL E.C.M.W.F. PHYSICS PACKAGE ON
! LAGPHY : LOGICAL : IF TRUE, PHYSICS PACKAGE CALLED IN LAGGED MODE
! LECOND : LOGICAL : TURN THE LARGE-SCALE CONDENSATION ON
! LECUMF : LOGICAL : TURN THE MASS-FLUX CUMULUS CONVECTION SCHEME ON
! LEDCLD : LOGICAL : TURN THE DIAGNOSTIC CLOUD SCHEME ON
! LEPCLD : LOGICAL : TURN THE PROGNOSTIC CLOUD SCHEME ON
! LEEVAP : LOGICAL : TURN THE EVAPORATION OF PRECIPITATION ON
! LEGWDG : LOGICAL : TURN THE GRAVITY WAVE DRAG ON
! LEGWWMS: LOGICAL : TURN THE WARNER-MCINTYRE-SCINOCCA NON-OROGRAPHIC GRAVITY WAVE SCHEME ON
! LEOZOC : LOGICAL : TURN THE CLIMATOLOGICAL OZONE ON
! LEQNGT : LOGICAL : TURN THE NEGATIVE HUMIDITY FIXER ON
! LERADI : LOGICAL : TURN THE RADIATION SCHEME ON
! LERADS : LOGICAL : TURN THE INTERACTIVE SURFACE RADIATIVE PROPERTIESON
! LESICE : LOGICAL : TURN THE INTERACTIVE SEA ICE PROCESSES ON
! LESURF : LOGICAL : TURN THE INTERACTIVE SURFACE PROCESSES ON
! LEVDIF : LOGICAL : TURN THE VERTICAL DIFFUSION ON
! LEO3CH : LOGICAL : TURN THE O3 CHEMISTRY ON (for EC prog. ozone)
! LO3CH_OLDVER : LOGICAL : USE OLD VERSION (v2.3) OF OZONE CHEMISTRY
! LECO2DIU: LOGICAL: UPDATE THE NBF CO2 FLUXES CLIMATOLOGY DURING THE RUN OF THE MODEL (introduce a diurnal cycle)
! LNEEONLINE: LOGICAL: USE ON-LINE CTESSEL IF TRUE 
! LBFASCO2 : LOGICAL : APPLY THE FLUX ADJUSTMENT TO GPP AND REC IN CTESSEL
! LBUD23 : LOGICAL : SWITCH FOR 3 AND 2 DIMENSIONAL BUDGETS 
! LBUDCYCLE: LOGICL: SWITCH FOR DIURNAL CYCLE DIAGNOSTICS
! LEMETHOX: LOGICAL: TURN THE METHANE OXIDATION ON
! LECURR : LOGICAL : IF TRUE, OCEAN CURRENT BOUNDARY CONDITION IS USED
! LVDFTRAC: LOGICAL: TURN TRACER TRANSPORT BY VERTICAL DIFFUSION ON 
! LMFTRAC: LOGICAL : TURN TRACER TRANSPORT BY MASS FLUX CONVECTION ON
! LMFSCAV:LOGICAL  : TURN TRACER WET SCAAVENGING IN CUMULUS CONVECTION SCHEME ON
! LERAIN : LOGICAL : RAIN ASSIMILATION
! LEMWAVE : LOGICAL : ALL-SKY RADIANCE ASSIMILATION
! LE4ALB : LOGICAL : MODIS ALBEDO ON (DIRECT+DIFFUSE)*(UVIS+NIR) 
! LEOCWA : LOGICAL : WARM OCEAN LAYER PARAMETRIZATION
! LEOBC  : LOGICAL : SST CORRECTION
! LEOBCICE : LOGICAL : ICE CORRECTION (IMPLIED IF LEOBC)
! LEOCCO : LOGICAL : COOL OCEAN SKIN PARAMETRIZATION
! LEOCSA : LOGICAL : SALINTY EFFECT ON SATURATION AT OCEAN SURFACE
! LEOCLA : LOGICAL : LANGMUIR CIRCULATION EFFECT IN SKIN LAYER SCHEME
! RTHRFRTI : INTEGER : MINIMUM FRACTION FOR ALL SURFACE TILES
! LE4ALB : LOGICAL  : MODIS ALBEDO (UV-Vis+NIR)x(direct+diffuse) 
! LEVGEN : LOGICAL  : VAN GENUCHTEN HYDROLOGY (with SOIL TYPE field)
! LESSRO : LOGICAL  : OROGRAPHIC (VIC-TYPE) RUNOFF
! LEFLAKE : LOGICAL  : LAKE MODEL FLAKE
! LEOCML : LOGICAL  : OCEAN MIX LAYER MODEL
! LEOCLAKE : LOGICAL  : PERSISTED LAKE SST and ICE
! LEOLAKESST : LOGICAL : USE LAKES TEMPERATURE AND ICE AS SST AND ICE ON LAKE POINTS
! LOCMLTKE : LOGICAL  : IF TRUE JANSSEN'S VERSION OF THE MELLOR-YAMADA SCHEME IS RUN.
! LECLIPQT0: LOGICAL: REMOVE NEGATIVE Q AND SUPERSATURATION AT INITIAL TIME
! LECLIPCLDT0: LOGICAL: REMOVE NEGATIVE CLOUD WATER/ICE AND BOUND CLOUD COVER AT INITIAL TIME
! LDUCTDIA : LOGICAL  : COMPUTATIONS AND ARCHIVING OF DUCTING DIAGNOSTICS
! LESN09 : LOGICAL  : IF true use the snow 2009 scheme (liquid water, density, snow cover fraction, exposed and forest albedo)
! LELAIV : LOGICAL  : IF FALSE OVERWRITE CLIMATE LAI FIELDS WITH LUT VALUES
! LESMOSS : LOGICAL : SMOS SEA SURFACE SALINITY MONITORING
! LECTESSEL : LOGICAL : LAND CARBON (CTESSEL) USED FOR CO2 FLUXES
! LEAGS   : LOGICAL : LAND CARBON (CTESSEL) USED FOR CO2 AND EVAP FLUXES
! RLAIINT : REAL    : INTERACTIVE LAI CLIM RELAXATION (1=interactive ; 0=clim)
! LEGBRAD : LOGICAL : ACTIVATE RADAR PRECIPITATION OBSERVATION OPERATOR
! NPRACCL : INTEGER : ACCUMULATION LENGTH FOR RADAR PRECIPITATION OBSERVATION ASSIMILATION
! LERAINGG : LOGICAL : ACTIVATE RAIN GAUGE OBSERVATION OPERATOR
! LECLIM10D: Logical: IF TRUE interpolate between 10-day climate values (for albedo and LAI) 
! LSPCRM : LOGICAL : ACTIVATES SUPER-PARAMETRIZATION SCHEME REPLACING MOIST PROCESSES.

!     -----------------------------------------------------------------
END MODULE YOEPHY
